# Dev
%dev.quarkus.console.color=true
# App
quarkus.banner.enabled=false
# Hibernate
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
# JWT
mp.jwt.verify.publickey.algorithm=ES256
# Openapi
quarkus.smallrye-openapi.info-title=Healthcare Appointment
quarkus.smallrye-openapi.info-description=API documentation for the Appointment Service of the Healthcare Platform. This service handles appointment management.
quarkus.smallrye-openapi.path=/api/appointment/openapi.json
quarkus.smallrye-openapi.scan-exclude-profiles=internal
quarkus.smallrye-openapi.auto-add-operation-summary=false
# Performance
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true
# SOAP client (Insurance)
quarkus.cxf.client.insurance-invoice-soap.client-endpoint-url=${INSURANCE_SOAP_ENDPOINT_URL:http://localhost:8082/ws/invoice}
