# Dev
%dev.quarkus.console.color=true
# App
quarkus.http.port=8081
quarkus.banner.enabled=false
# Hibernate
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
# JWT
mp.jwt.verify.publickey.algorithm=ES256
# Openapi
quarkus.smallrye-openapi.info-title=Healthcare EHR
quarkus.smallrye-openapi.info-description=API documentation for the EHR Service of the Healthcare Platform. This service handles EHR management.
quarkus.smallrye-openapi.path=/api/ehr/openapi.json
quarkus.smallrye-openapi.scan-exclude-profiles=internal
quarkus.smallrye-openapi.auto-add-operation-summary=false
# Performance
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true
