// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
  DeleteApiAppointmentByIdData,
  DeleteApiAppointmentByIdErrors,
  DeleteApiAppointmentByIdResponses,
  DeleteApiDoctorByIdData,
  DeleteApiDoctorByIdErrors,
  DeleteApiDoctorByIdResponses,
  DeleteApiFacilityByIdData,
  DeleteApiFacilityByIdErrors,
  DeleteApiFacilityByIdResponses,
  DeleteApiSpecialtyByIdData,
  DeleteApiSpecialtyByIdErrors,
  DeleteApiSpecialtyByIdResponses,
  GetApiAppointmentByIdData,
  GetApiAppointmentByIdErrors,
  GetApiAppointmentByIdResponses,
  GetApiAppointmentCountData,
  GetApiAppointmentCountErrors,
  GetApiAppointmentCountResponses,
  GetApiAppointmentData,
  GetApiAppointmentErrors,
  GetApiAppointmentResponses,
  GetApiDoctorByIdData,
  GetApiDoctorByIdErrors,
  GetApiDoctorByIdResponses,
  GetApiDoctorCountData,
  GetApiDoctorCountErrors,
  GetApiDoctorCountResponses,
  GetApiDoctorData,
  GetApiDoctorErrors,
  GetApiDoctorResponses,
  GetApiFacilityByIdData,
  GetApiFacilityByIdErrors,
  GetApiFacilityByIdResponses,
  GetApiFacilityCountData,
  GetApiFacilityCountErrors,
  GetApiFacilityCountResponses,
  GetApiFacilityData,
  GetApiFacilityErrors,
  GetApiFacilityResponses,
  GetApiSpecialtyByIdData,
  GetApiSpecialtyByIdErrors,
  GetApiSpecialtyByIdResponses,
  GetApiSpecialtyCountData,
  GetApiSpecialtyCountErrors,
  GetApiSpecialtyCountResponses,
  GetApiSpecialtyData,
  GetApiSpecialtyErrors,
  GetApiSpecialtyResponses,
  PostApiAppointmentData,
  PostApiAppointmentErrors,
  PostApiAppointmentResponses,
  PostApiDoctorData,
  PostApiDoctorErrors,
  PostApiDoctorResponses,
  PostApiFacilityData,
  PostApiFacilityErrors,
  PostApiFacilityResponses,
  PostApiSpecialtyData,
  PostApiSpecialtyErrors,
  PostApiSpecialtyResponses,
  PutApiAppointmentByIdData,
  PutApiAppointmentByIdErrors,
  PutApiAppointmentByIdResponses,
  PutApiDoctorByIdData,
  PutApiDoctorByIdErrors,
  PutApiDoctorByIdResponses,
  PutApiFacilityByIdData,
  PutApiFacilityByIdErrors,
  PutApiFacilityByIdResponses,
  PutApiSpecialtyByIdData,
  PutApiSpecialtyByIdErrors,
  PutApiSpecialtyByIdResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const getApiAppointment = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAppointmentData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiAppointmentResponses,
    GetApiAppointmentErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment",
    ...options,
  })

export const postApiAppointment = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAppointmentData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAppointmentResponses,
    PostApiAppointmentErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiAppointmentCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAppointmentCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiAppointmentCountResponses,
    GetApiAppointmentCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment/count",
    ...options,
  })

export const deleteApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiAppointmentByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiAppointmentByIdResponses,
    DeleteApiAppointmentByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment/{id}",
    ...options,
  })

export const getApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAppointmentByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiAppointmentByIdResponses,
    GetApiAppointmentByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment/{id}",
    ...options,
  })

export const putApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiAppointmentByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiAppointmentByIdResponses,
    PutApiAppointmentByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiDoctor = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiDoctorData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiDoctorResponses,
    GetApiDoctorErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/doctor",
    ...options,
  })

export const postApiDoctor = <ThrowOnError extends boolean = false>(
  options: Options<PostApiDoctorData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiDoctorResponses,
    PostApiDoctorErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/doctor",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiDoctorCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiDoctorCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiDoctorCountResponses,
    GetApiDoctorCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/doctor/count",
    ...options,
  })

export const deleteApiDoctorById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiDoctorByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiDoctorByIdResponses,
    DeleteApiDoctorByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/doctor/{id}",
    ...options,
  })

export const getApiDoctorById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiDoctorByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiDoctorByIdResponses,
    GetApiDoctorByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/doctor/{id}",
    ...options,
  })

export const putApiDoctorById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiDoctorByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiDoctorByIdResponses,
    PutApiDoctorByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/doctor/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiFacility = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiFacilityData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiFacilityResponses,
    GetApiFacilityErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/facility",
    ...options,
  })

export const postApiFacility = <ThrowOnError extends boolean = false>(
  options: Options<PostApiFacilityData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiFacilityResponses,
    PostApiFacilityErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/facility",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiFacilityCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiFacilityCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiFacilityCountResponses,
    GetApiFacilityCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/facility/count",
    ...options,
  })

export const deleteApiFacilityById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiFacilityByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiFacilityByIdResponses,
    DeleteApiFacilityByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/facility/{id}",
    ...options,
  })

export const getApiFacilityById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiFacilityByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiFacilityByIdResponses,
    GetApiFacilityByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/facility/{id}",
    ...options,
  })

export const putApiFacilityById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiFacilityByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiFacilityByIdResponses,
    PutApiFacilityByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/facility/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiSpecialty = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSpecialtyData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiSpecialtyResponses,
    GetApiSpecialtyErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/specialty",
    ...options,
  })

export const postApiSpecialty = <ThrowOnError extends boolean = false>(
  options: Options<PostApiSpecialtyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiSpecialtyResponses,
    PostApiSpecialtyErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/specialty",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiSpecialtyCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSpecialtyCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiSpecialtyCountResponses,
    GetApiSpecialtyCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/specialty/count",
    ...options,
  })

export const deleteApiSpecialtyById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiSpecialtyByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiSpecialtyByIdResponses,
    DeleteApiSpecialtyByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/specialty/{id}",
    ...options,
  })

export const getApiSpecialtyById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiSpecialtyByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiSpecialtyByIdResponses,
    GetApiSpecialtyByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/specialty/{id}",
    ...options,
  })

export const putApiSpecialtyById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiSpecialtyByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiSpecialtyByIdResponses,
    PutApiSpecialtyByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/specialty/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
