// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
  DeleteApiAppointmentByIdData,
  DeleteApiAppointmentByIdErrors,
  DeleteApiAppointmentByIdResponses,
  DeleteApiClinicalEpisodeByIdData,
  DeleteApiClinicalEpisodeByIdErrors,
  DeleteApiClinicalEpisodeByIdResponses,
  DeleteApiDoctorByIdData,
  DeleteApiDoctorByIdErrors,
  DeleteApiDoctorByIdResponses,
  DeleteApiFacilityByIdData,
  DeleteApiFacilityByIdErrors,
  DeleteApiFacilityByIdResponses,
  DeleteApiHealthRecordByIdData,
  DeleteApiHealthRecordByIdErrors,
  DeleteApiHealthRecordByIdResponses,
  DeleteApiInsuranceInvoiceByIdData,
  DeleteApiInsuranceInvoiceByIdErrors,
  DeleteApiInsuranceInvoiceByIdResponses,
  DeleteApiInsuranceProviderByIdData,
  DeleteApiInsuranceProviderByIdErrors,
  DeleteApiInsuranceProviderByIdResponses,
  DeleteApiPatientByIdData,
  DeleteApiPatientByIdErrors,
  DeleteApiPatientByIdResponses,
  DeleteApiPrescriptionByIdData,
  DeleteApiPrescriptionByIdErrors,
  DeleteApiPrescriptionByIdResponses,
  DeleteApiSpecialtyByIdData,
  DeleteApiSpecialtyByIdErrors,
  DeleteApiSpecialtyByIdResponses,
  GetApiAppointmentByIdData,
  GetApiAppointmentByIdErrors,
  GetApiAppointmentByIdResponses,
  GetApiAppointmentCountData,
  GetApiAppointmentCountErrors,
  GetApiAppointmentCountResponses,
  GetApiAppointmentData,
  GetApiAppointmentErrors,
  GetApiAppointmentResponses,
  GetApiClinicalEpisodeByIdData,
  GetApiClinicalEpisodeByIdErrors,
  GetApiClinicalEpisodeByIdResponses,
  GetApiClinicalEpisodeCountData,
  GetApiClinicalEpisodeCountErrors,
  GetApiClinicalEpisodeCountResponses,
  GetApiClinicalEpisodeData,
  GetApiClinicalEpisodeErrors,
  GetApiClinicalEpisodeResponses,
  GetApiDoctorByIdData,
  GetApiDoctorByIdErrors,
  GetApiDoctorByIdResponses,
  GetApiDoctorCountData,
  GetApiDoctorCountErrors,
  GetApiDoctorCountResponses,
  GetApiDoctorData,
  GetApiDoctorErrors,
  GetApiDoctorResponses,
  GetApiFacilityByIdData,
  GetApiFacilityByIdErrors,
  GetApiFacilityByIdResponses,
  GetApiFacilityCountData,
  GetApiFacilityCountErrors,
  GetApiFacilityCountResponses,
  GetApiFacilityData,
  GetApiFacilityErrors,
  GetApiFacilityResponses,
  GetApiHealthRecordByIdData,
  GetApiHealthRecordByIdErrors,
  GetApiHealthRecordByIdResponses,
  GetApiHealthRecordCountData,
  GetApiHealthRecordCountErrors,
  GetApiHealthRecordCountResponses,
  GetApiHealthRecordData,
  GetApiHealthRecordErrors,
  GetApiHealthRecordResponses,
  GetApiInsuranceInvoiceByIdData,
  GetApiInsuranceInvoiceByIdErrors,
  GetApiInsuranceInvoiceByIdResponses,
  GetApiInsuranceInvoiceCountData,
  GetApiInsuranceInvoiceCountErrors,
  GetApiInsuranceInvoiceCountResponses,
  GetApiInsuranceInvoiceData,
  GetApiInsuranceInvoiceErrors,
  GetApiInsuranceInvoiceResponses,
  GetApiInsuranceProviderByIdData,
  GetApiInsuranceProviderByIdErrors,
  GetApiInsuranceProviderByIdResponses,
  GetApiInsuranceProviderCountData,
  GetApiInsuranceProviderCountErrors,
  GetApiInsuranceProviderCountResponses,
  GetApiInsuranceProviderData,
  GetApiInsuranceProviderErrors,
  GetApiInsuranceProviderResponses,
  GetApiPatientByIdData,
  GetApiPatientByIdErrors,
  GetApiPatientByIdResponses,
  GetApiPatientCountData,
  GetApiPatientCountErrors,
  GetApiPatientCountResponses,
  GetApiPatientData,
  GetApiPatientErrors,
  GetApiPatientResponses,
  GetApiPrescriptionByIdData,
  GetApiPrescriptionByIdErrors,
  GetApiPrescriptionByIdResponses,
  GetApiPrescriptionCountData,
  GetApiPrescriptionCountErrors,
  GetApiPrescriptionCountResponses,
  GetApiPrescriptionData,
  GetApiPrescriptionErrors,
  GetApiPrescriptionResponses,
  GetApiSpecialtyByIdData,
  GetApiSpecialtyByIdErrors,
  GetApiSpecialtyByIdResponses,
  GetApiSpecialtyCountData,
  GetApiSpecialtyCountErrors,
  GetApiSpecialtyCountResponses,
  GetApiSpecialtyData,
  GetApiSpecialtyErrors,
  GetApiSpecialtyResponses,
  PostApiAppointmentData,
  PostApiAppointmentErrors,
  PostApiAppointmentResponses,
  PostApiAppointmentValidateData,
  PostApiAppointmentValidateErrors,
  PostApiAppointmentValidateResponses,
  PostApiClinicalEpisodeData,
  PostApiClinicalEpisodeErrors,
  PostApiClinicalEpisodeResponses,
  PostApiDoctorData,
  PostApiDoctorErrors,
  PostApiDoctorResponses,
  PostApiFacilityData,
  PostApiFacilityErrors,
  PostApiFacilityResponses,
  PostApiHealthRecordData,
  PostApiHealthRecordErrors,
  PostApiHealthRecordResponses,
  PostApiInsuranceInvoiceData,
  PostApiInsuranceInvoiceErrors,
  PostApiInsuranceInvoiceResponses,
  PostApiInsuranceProviderData,
  PostApiInsuranceProviderErrors,
  PostApiInsuranceProviderResponses,
  PostApiPatientData,
  PostApiPatientErrors,
  PostApiPatientResponses,
  PostApiPrescriptionData,
  PostApiPrescriptionErrors,
  PostApiPrescriptionResponses,
  PostApiSpecialtyData,
  PostApiSpecialtyErrors,
  PostApiSpecialtyResponses,
  PutApiAppointmentByIdData,
  PutApiAppointmentByIdErrors,
  PutApiAppointmentByIdResponses,
  PutApiClinicalEpisodeByIdData,
  PutApiClinicalEpisodeByIdErrors,
  PutApiClinicalEpisodeByIdResponses,
  PutApiDoctorByIdData,
  PutApiDoctorByIdErrors,
  PutApiDoctorByIdResponses,
  PutApiFacilityByIdData,
  PutApiFacilityByIdErrors,
  PutApiFacilityByIdResponses,
  PutApiHealthRecordByIdData,
  PutApiHealthRecordByIdErrors,
  PutApiHealthRecordByIdResponses,
  PutApiInsuranceInvoiceByIdData,
  PutApiInsuranceInvoiceByIdErrors,
  PutApiInsuranceInvoiceByIdResponses,
  PutApiInsuranceProviderByIdData,
  PutApiInsuranceProviderByIdErrors,
  PutApiInsuranceProviderByIdResponses,
  PutApiPatientByIdData,
  PutApiPatientByIdErrors,
  PutApiPatientByIdResponses,
  PutApiPrescriptionByIdData,
  PutApiPrescriptionByIdErrors,
  PutApiPrescriptionByIdResponses,
  PutApiSpecialtyByIdData,
  PutApiSpecialtyByIdErrors,
  PutApiSpecialtyByIdResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const getApiAppointment = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAppointmentData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiAppointmentResponses,
    GetApiAppointmentErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/appointment",
    ...options,
  })

export const postApiAppointment = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAppointmentData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAppointmentResponses,
    PostApiAppointmentErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/appointment",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiAppointmentCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAppointmentCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiAppointmentCountResponses,
    GetApiAppointmentCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/appointment/count",
    ...options,
  })

/**
 * Validate appointment scheduling rules
 */
export const postApiAppointmentValidate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiAppointmentValidateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAppointmentValidateResponses,
    PostApiAppointmentValidateErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/appointment/validate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const deleteApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiAppointmentByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiAppointmentByIdResponses,
    DeleteApiAppointmentByIdErrors,
    ThrowOnError
  >({ url: "/api/appointment/{id}", ...options })

export const getApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAppointmentByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiAppointmentByIdResponses,
    GetApiAppointmentByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/appointment/{id}",
    ...options,
  })

export const putApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiAppointmentByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiAppointmentByIdResponses,
    PutApiAppointmentByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/appointment/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiDoctor = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiDoctorData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiDoctorResponses,
    GetApiDoctorErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/doctor",
    ...options,
  })

export const postApiDoctor = <ThrowOnError extends boolean = false>(
  options: Options<PostApiDoctorData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiDoctorResponses,
    PostApiDoctorErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/doctor",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiDoctorCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiDoctorCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiDoctorCountResponses,
    GetApiDoctorCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/doctor/count",
    ...options,
  })

export const deleteApiDoctorById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiDoctorByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiDoctorByIdResponses,
    DeleteApiDoctorByIdErrors,
    ThrowOnError
  >({ url: "/api/doctor/{id}", ...options })

export const getApiDoctorById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiDoctorByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiDoctorByIdResponses,
    GetApiDoctorByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/doctor/{id}",
    ...options,
  })

export const putApiDoctorById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiDoctorByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiDoctorByIdResponses,
    PutApiDoctorByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/doctor/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiFacility = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiFacilityData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiFacilityResponses,
    GetApiFacilityErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/facility",
    ...options,
  })

export const postApiFacility = <ThrowOnError extends boolean = false>(
  options: Options<PostApiFacilityData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiFacilityResponses,
    PostApiFacilityErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/facility",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiFacilityCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiFacilityCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiFacilityCountResponses,
    GetApiFacilityCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/facility/count",
    ...options,
  })

export const deleteApiFacilityById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiFacilityByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiFacilityByIdResponses,
    DeleteApiFacilityByIdErrors,
    ThrowOnError
  >({ url: "/api/facility/{id}", ...options })

export const getApiFacilityById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiFacilityByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiFacilityByIdResponses,
    GetApiFacilityByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/facility/{id}",
    ...options,
  })

export const putApiFacilityById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiFacilityByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiFacilityByIdResponses,
    PutApiFacilityByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/facility/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiSpecialty = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSpecialtyData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiSpecialtyResponses,
    GetApiSpecialtyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/specialty",
    ...options,
  })

export const postApiSpecialty = <ThrowOnError extends boolean = false>(
  options: Options<PostApiSpecialtyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiSpecialtyResponses,
    PostApiSpecialtyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/specialty",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiSpecialtyCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSpecialtyCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiSpecialtyCountResponses,
    GetApiSpecialtyCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/specialty/count",
    ...options,
  })

export const deleteApiSpecialtyById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiSpecialtyByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiSpecialtyByIdResponses,
    DeleteApiSpecialtyByIdErrors,
    ThrowOnError
  >({ url: "/api/specialty/{id}", ...options })

export const getApiSpecialtyById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiSpecialtyByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiSpecialtyByIdResponses,
    GetApiSpecialtyByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/specialty/{id}",
    ...options,
  })

export const putApiSpecialtyById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiSpecialtyByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiSpecialtyByIdResponses,
    PutApiSpecialtyByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/specialty/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiClinicalEpisode = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiClinicalEpisodeData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiClinicalEpisodeResponses,
    GetApiClinicalEpisodeErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/clinical-episode",
    ...options,
  })

export const postApiClinicalEpisode = <ThrowOnError extends boolean = false>(
  options: Options<PostApiClinicalEpisodeData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiClinicalEpisodeResponses,
    PostApiClinicalEpisodeErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/clinical-episode",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiClinicalEpisodeCount = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiClinicalEpisodeCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiClinicalEpisodeCountResponses,
    GetApiClinicalEpisodeCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/clinical-episode/count",
    ...options,
  })

export const deleteApiClinicalEpisodeById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiClinicalEpisodeByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiClinicalEpisodeByIdResponses,
    DeleteApiClinicalEpisodeByIdErrors,
    ThrowOnError
  >({ url: "/api/clinical-episode/{id}", ...options })

export const getApiClinicalEpisodeById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiClinicalEpisodeByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiClinicalEpisodeByIdResponses,
    GetApiClinicalEpisodeByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/clinical-episode/{id}",
    ...options,
  })

export const putApiClinicalEpisodeById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiClinicalEpisodeByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiClinicalEpisodeByIdResponses,
    PutApiClinicalEpisodeByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/clinical-episode/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiHealthRecord = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiHealthRecordData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiHealthRecordResponses,
    GetApiHealthRecordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/health-record",
    ...options,
  })

export const postApiHealthRecord = <ThrowOnError extends boolean = false>(
  options: Options<PostApiHealthRecordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiHealthRecordResponses,
    PostApiHealthRecordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/health-record",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiHealthRecordCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiHealthRecordCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiHealthRecordCountResponses,
    GetApiHealthRecordCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/health-record/count",
    ...options,
  })

export const deleteApiHealthRecordById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiHealthRecordByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiHealthRecordByIdResponses,
    DeleteApiHealthRecordByIdErrors,
    ThrowOnError
  >({ url: "/api/health-record/{id}", ...options })

export const getApiHealthRecordById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiHealthRecordByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiHealthRecordByIdResponses,
    GetApiHealthRecordByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/health-record/{id}",
    ...options,
  })

export const putApiHealthRecordById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiHealthRecordByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiHealthRecordByIdResponses,
    PutApiHealthRecordByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/health-record/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiPatient = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPatientData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiPatientResponses,
    GetApiPatientErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/patient",
    ...options,
  })

export const postApiPatient = <ThrowOnError extends boolean = false>(
  options: Options<PostApiPatientData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiPatientResponses,
    PostApiPatientErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/patient",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiPatientCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPatientCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiPatientCountResponses,
    GetApiPatientCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/patient/count",
    ...options,
  })

export const deleteApiPatientById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiPatientByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiPatientByIdResponses,
    DeleteApiPatientByIdErrors,
    ThrowOnError
  >({ url: "/api/patient/{id}", ...options })

export const getApiPatientById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiPatientByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiPatientByIdResponses,
    GetApiPatientByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/patient/{id}",
    ...options,
  })

export const putApiPatientById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiPatientByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiPatientByIdResponses,
    PutApiPatientByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/patient/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiPrescription = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPrescriptionData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiPrescriptionResponses,
    GetApiPrescriptionErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/prescription",
    ...options,
  })

export const postApiPrescription = <ThrowOnError extends boolean = false>(
  options: Options<PostApiPrescriptionData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiPrescriptionResponses,
    PostApiPrescriptionErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/prescription",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiPrescriptionCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPrescriptionCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiPrescriptionCountResponses,
    GetApiPrescriptionCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/prescription/count",
    ...options,
  })

export const deleteApiPrescriptionById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiPrescriptionByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiPrescriptionByIdResponses,
    DeleteApiPrescriptionByIdErrors,
    ThrowOnError
  >({ url: "/api/prescription/{id}", ...options })

export const getApiPrescriptionById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiPrescriptionByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiPrescriptionByIdResponses,
    GetApiPrescriptionByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/prescription/{id}",
    ...options,
  })

export const putApiPrescriptionById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiPrescriptionByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiPrescriptionByIdResponses,
    PutApiPrescriptionByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/prescription/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiInsuranceInvoice = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiInsuranceInvoiceData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiInsuranceInvoiceResponses,
    GetApiInsuranceInvoiceErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/insurance/invoice",
    ...options,
  })

export const postApiInsuranceInvoice = <ThrowOnError extends boolean = false>(
  options: Options<PostApiInsuranceInvoiceData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiInsuranceInvoiceResponses,
    PostApiInsuranceInvoiceErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/insurance/invoice",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiInsuranceInvoiceCount = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiInsuranceInvoiceCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiInsuranceInvoiceCountResponses,
    GetApiInsuranceInvoiceCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/insurance/invoice/count",
    ...options,
  })

export const deleteApiInsuranceInvoiceById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiInsuranceInvoiceByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiInsuranceInvoiceByIdResponses,
    DeleteApiInsuranceInvoiceByIdErrors,
    ThrowOnError
  >({ url: "/api/insurance/invoice/{id}", ...options })

export const getApiInsuranceInvoiceById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiInsuranceInvoiceByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiInsuranceInvoiceByIdResponses,
    GetApiInsuranceInvoiceByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/insurance/invoice/{id}",
    ...options,
  })

export const putApiInsuranceInvoiceById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutApiInsuranceInvoiceByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiInsuranceInvoiceByIdResponses,
    PutApiInsuranceInvoiceByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/insurance/invoice/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiInsuranceProvider = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiInsuranceProviderData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiInsuranceProviderResponses,
    GetApiInsuranceProviderErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/insurance/provider",
    ...options,
  })

export const postApiInsuranceProvider = <ThrowOnError extends boolean = false>(
  options: Options<PostApiInsuranceProviderData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiInsuranceProviderResponses,
    PostApiInsuranceProviderErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/insurance/provider",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiInsuranceProviderCount = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiInsuranceProviderCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiInsuranceProviderCountResponses,
    GetApiInsuranceProviderCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/insurance/provider/count",
    ...options,
  })

export const deleteApiInsuranceProviderById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiInsuranceProviderByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiInsuranceProviderByIdResponses,
    DeleteApiInsuranceProviderByIdErrors,
    ThrowOnError
  >({ url: "/api/insurance/provider/{id}", ...options })

export const getApiInsuranceProviderById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiInsuranceProviderByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiInsuranceProviderByIdResponses,
    GetApiInsuranceProviderByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/insurance/provider/{id}",
    ...options,
  })

export const putApiInsuranceProviderById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutApiInsuranceProviderByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiInsuranceProviderByIdResponses,
    PutApiInsuranceProviderByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/insurance/provider/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
