// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://localhost:4321" | (string & {})
}

export type OpenapiAppointment = {
  id: OpenapiUuid
  patient: OpenapiPatient
  doctor: OpenapiDoctor
  facility: OpenapiFacility
  scheduledDate: OpenapiLocalDateTime
  status?: OpenapiAppointmentStatus
}

export type OpenapiAppointmentStatus = "PENDING" | "COMPLETED" | "CANCELED"

export type OpenapiDoctor = {
  id: OpenapiUuid
  medicalLicense: string
  firstName: string
  lastName: string
  specialties?: Array<OpenapiSpecialty>
  facilities?: Array<OpenapiFacility>
}

export type OpenapiFacility = {
  id: OpenapiUuid
  name: string
  address: string
}

/**
 * HTTP Problem Response according to RFC9457 and RFC7807
 */
export type OpenapiHttpProblem = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status?: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance?: string
  [key: string]: unknown
}

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export type OpenapiHttpValidationProblem = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status?: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance?: string
  /**
   * List of validation constraint violations that occurred
   */
  violations?: Array<OpenapiViolation>
  [key: string]: unknown
}

export type OpenapiLocalDateTime = string

export type OpenapiPatient = {
  id: OpenapiUuid
  nationalId: string
  phone: string
}

export type OpenapiSpecialty = {
  id: OpenapiUuid
  name: string
}

export type OpenapiUuid = string

/**
 * Validation constraint violation details
 */
export type OpenapiViolation = {
  /**
   * The field for which the validation failed
   */
  field?: string
  /**
   * Part of the http request where the validation error occurred such as query, path, header, form, body
   */
  in?: string
  /**
   * Description of the validation error
   */
  message?: string
}

export type OpenapiClinicalEpisode = {
  id: OpenapiUuid
  healthRecord: OpenapiHealthRecord
  appointment: OpenapiAppointment
  diagnosis: string
  treatmentPlan?: string
  recordedAt?: OpenapiLocalDateTime
}

export type OpenapiHealthRecord = {
  id: OpenapiUuid
  status?: OpenapiHealthRecordStatus
  createdAt?: OpenapiLocalDateTime
  patient: OpenapiPatient
}

export type OpenapiHealthRecordStatus = "ACTIVE" | "INACTIVE"

export type OpenapiPrescription = {
  id: OpenapiUuid
  clinicalEpisode: OpenapiClinicalEpisode
  medicationDetails: string
  instructions: string
  issuedAt?: OpenapiLocalDateTime
}

export type OpenapiInsuranceProvider = {
  id: OpenapiUuid
  name: string
  coverageDetails?: string
}

export type OpenapiInvoice = {
  id: OpenapiUuid
  appointment: OpenapiAppointment
  insuranceProvider?: OpenapiInsuranceProvider
  totalAmount: number
  paymentMethod: string
  issuedAt?: OpenapiLocalDateTime
}

export type GetApiAppointmentData = {
  body?: never
  path?: never
  query?: {
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/appointment"
}

export type GetApiAppointmentErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiAppointmentResponses = {
  /**
   * OK
   */
  200: Array<OpenapiAppointment>
}

export type GetApiAppointmentResponse =
  GetApiAppointmentResponses[keyof GetApiAppointmentResponses]

export type PostApiAppointmentData = {
  body: OpenapiAppointment
  path?: never
  query?: never
  url: "/api/appointment"
}

export type PostApiAppointmentErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiAppointmentResponses = {
  201: OpenapiAppointment
}

export type PostApiAppointmentResponse =
  PostApiAppointmentResponses[keyof PostApiAppointmentResponses]

export type GetApiAppointmentCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/appointment/count"
}

export type GetApiAppointmentCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiAppointmentCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiAppointmentCountResponse =
  GetApiAppointmentCountResponses[keyof GetApiAppointmentCountResponses]

export type DeleteApiAppointmentByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/appointment/{id}"
}

export type DeleteApiAppointmentByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiAppointmentByIdResponses = {
  204: void
}

export type DeleteApiAppointmentByIdResponse =
  DeleteApiAppointmentByIdResponses[keyof DeleteApiAppointmentByIdResponses]

export type GetApiAppointmentByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/appointment/{id}"
}

export type GetApiAppointmentByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiAppointmentByIdResponses = {
  /**
   * OK
   */
  200: OpenapiAppointment
}

export type GetApiAppointmentByIdResponse =
  GetApiAppointmentByIdResponses[keyof GetApiAppointmentByIdResponses]

export type PutApiAppointmentByIdData = {
  body: OpenapiAppointment
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/appointment/{id}"
}

export type PutApiAppointmentByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiAppointmentByIdResponses = {
  201: OpenapiAppointment
}

export type PutApiAppointmentByIdResponse =
  PutApiAppointmentByIdResponses[keyof PutApiAppointmentByIdResponses]

export type GetApiDoctorData = {
  body?: never
  path?: never
  query?: {
    firstName?: string
    lastName?: string
    medicalLicense?: string
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/doctor"
}

export type GetApiDoctorErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiDoctorResponses = {
  /**
   * OK
   */
  200: Array<OpenapiDoctor>
}

export type GetApiDoctorResponse =
  GetApiDoctorResponses[keyof GetApiDoctorResponses]

export type PostApiDoctorData = {
  body: OpenapiDoctor
  path?: never
  query?: never
  url: "/api/doctor"
}

export type PostApiDoctorErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiDoctorResponses = {
  201: OpenapiDoctor
}

export type PostApiDoctorResponse =
  PostApiDoctorResponses[keyof PostApiDoctorResponses]

export type GetApiDoctorCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/doctor/count"
}

export type GetApiDoctorCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiDoctorCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiDoctorCountResponse =
  GetApiDoctorCountResponses[keyof GetApiDoctorCountResponses]

export type DeleteApiDoctorByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/doctor/{id}"
}

export type DeleteApiDoctorByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiDoctorByIdResponses = {
  204: void
}

export type DeleteApiDoctorByIdResponse =
  DeleteApiDoctorByIdResponses[keyof DeleteApiDoctorByIdResponses]

export type GetApiDoctorByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/doctor/{id}"
}

export type GetApiDoctorByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiDoctorByIdResponses = {
  /**
   * OK
   */
  200: OpenapiDoctor
}

export type GetApiDoctorByIdResponse =
  GetApiDoctorByIdResponses[keyof GetApiDoctorByIdResponses]

export type PutApiDoctorByIdData = {
  body: OpenapiDoctor
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/doctor/{id}"
}

export type PutApiDoctorByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiDoctorByIdResponses = {
  201: OpenapiDoctor
}

export type PutApiDoctorByIdResponse =
  PutApiDoctorByIdResponses[keyof PutApiDoctorByIdResponses]

export type GetApiFacilityData = {
  body?: never
  path?: never
  query?: {
    address?: string
    name?: string
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/facility"
}

export type GetApiFacilityErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiFacilityResponses = {
  /**
   * OK
   */
  200: Array<OpenapiFacility>
}

export type GetApiFacilityResponse =
  GetApiFacilityResponses[keyof GetApiFacilityResponses]

export type PostApiFacilityData = {
  body: OpenapiFacility
  path?: never
  query?: never
  url: "/api/facility"
}

export type PostApiFacilityErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiFacilityResponses = {
  201: OpenapiFacility
}

export type PostApiFacilityResponse =
  PostApiFacilityResponses[keyof PostApiFacilityResponses]

export type GetApiFacilityCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/facility/count"
}

export type GetApiFacilityCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiFacilityCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiFacilityCountResponse =
  GetApiFacilityCountResponses[keyof GetApiFacilityCountResponses]

export type DeleteApiFacilityByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/facility/{id}"
}

export type DeleteApiFacilityByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiFacilityByIdResponses = {
  204: void
}

export type DeleteApiFacilityByIdResponse =
  DeleteApiFacilityByIdResponses[keyof DeleteApiFacilityByIdResponses]

export type GetApiFacilityByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/facility/{id}"
}

export type GetApiFacilityByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiFacilityByIdResponses = {
  /**
   * OK
   */
  200: OpenapiFacility
}

export type GetApiFacilityByIdResponse =
  GetApiFacilityByIdResponses[keyof GetApiFacilityByIdResponses]

export type PutApiFacilityByIdData = {
  body: OpenapiFacility
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/facility/{id}"
}

export type PutApiFacilityByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiFacilityByIdResponses = {
  201: OpenapiFacility
}

export type PutApiFacilityByIdResponse =
  PutApiFacilityByIdResponses[keyof PutApiFacilityByIdResponses]

export type GetApiSpecialtyData = {
  body?: never
  path?: never
  query?: {
    name?: string
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/specialty"
}

export type GetApiSpecialtyErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiSpecialtyResponses = {
  /**
   * OK
   */
  200: Array<OpenapiSpecialty>
}

export type GetApiSpecialtyResponse =
  GetApiSpecialtyResponses[keyof GetApiSpecialtyResponses]

export type PostApiSpecialtyData = {
  body: OpenapiSpecialty
  path?: never
  query?: never
  url: "/api/specialty"
}

export type PostApiSpecialtyErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiSpecialtyResponses = {
  201: OpenapiSpecialty
}

export type PostApiSpecialtyResponse =
  PostApiSpecialtyResponses[keyof PostApiSpecialtyResponses]

export type GetApiSpecialtyCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/specialty/count"
}

export type GetApiSpecialtyCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiSpecialtyCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiSpecialtyCountResponse =
  GetApiSpecialtyCountResponses[keyof GetApiSpecialtyCountResponses]

export type DeleteApiSpecialtyByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/specialty/{id}"
}

export type DeleteApiSpecialtyByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiSpecialtyByIdResponses = {
  204: void
}

export type DeleteApiSpecialtyByIdResponse =
  DeleteApiSpecialtyByIdResponses[keyof DeleteApiSpecialtyByIdResponses]

export type GetApiSpecialtyByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/specialty/{id}"
}

export type GetApiSpecialtyByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiSpecialtyByIdResponses = {
  /**
   * OK
   */
  200: OpenapiSpecialty
}

export type GetApiSpecialtyByIdResponse =
  GetApiSpecialtyByIdResponses[keyof GetApiSpecialtyByIdResponses]

export type PutApiSpecialtyByIdData = {
  body: OpenapiSpecialty
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/specialty/{id}"
}

export type PutApiSpecialtyByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiSpecialtyByIdResponses = {
  201: OpenapiSpecialty
}

export type PutApiSpecialtyByIdResponse =
  PutApiSpecialtyByIdResponses[keyof PutApiSpecialtyByIdResponses]

export type GetApiClinicalEpisodeData = {
  body?: never
  path?: never
  query?: {
    diagnosis?: string
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
    treatmentPlan?: string
  }
  url: "/api/clinical-episode"
}

export type GetApiClinicalEpisodeErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiClinicalEpisodeResponses = {
  /**
   * OK
   */
  200: Array<OpenapiClinicalEpisode>
}

export type GetApiClinicalEpisodeResponse =
  GetApiClinicalEpisodeResponses[keyof GetApiClinicalEpisodeResponses]

export type PostApiClinicalEpisodeData = {
  body: OpenapiClinicalEpisode
  path?: never
  query?: never
  url: "/api/clinical-episode"
}

export type PostApiClinicalEpisodeErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiClinicalEpisodeResponses = {
  201: OpenapiClinicalEpisode
}

export type PostApiClinicalEpisodeResponse =
  PostApiClinicalEpisodeResponses[keyof PostApiClinicalEpisodeResponses]

export type GetApiClinicalEpisodeCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/clinical-episode/count"
}

export type GetApiClinicalEpisodeCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiClinicalEpisodeCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiClinicalEpisodeCountResponse =
  GetApiClinicalEpisodeCountResponses[keyof GetApiClinicalEpisodeCountResponses]

export type DeleteApiClinicalEpisodeByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/clinical-episode/{id}"
}

export type DeleteApiClinicalEpisodeByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiClinicalEpisodeByIdResponses = {
  204: void
}

export type DeleteApiClinicalEpisodeByIdResponse =
  DeleteApiClinicalEpisodeByIdResponses[keyof DeleteApiClinicalEpisodeByIdResponses]

export type GetApiClinicalEpisodeByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/clinical-episode/{id}"
}

export type GetApiClinicalEpisodeByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiClinicalEpisodeByIdResponses = {
  /**
   * OK
   */
  200: OpenapiClinicalEpisode
}

export type GetApiClinicalEpisodeByIdResponse =
  GetApiClinicalEpisodeByIdResponses[keyof GetApiClinicalEpisodeByIdResponses]

export type PutApiClinicalEpisodeByIdData = {
  body: OpenapiClinicalEpisode
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/clinical-episode/{id}"
}

export type PutApiClinicalEpisodeByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiClinicalEpisodeByIdResponses = {
  201: OpenapiClinicalEpisode
}

export type PutApiClinicalEpisodeByIdResponse =
  PutApiClinicalEpisodeByIdResponses[keyof PutApiClinicalEpisodeByIdResponses]

export type GetApiHealthRecordData = {
  body?: never
  path?: never
  query?: {
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/health-record"
}

export type GetApiHealthRecordErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiHealthRecordResponses = {
  /**
   * OK
   */
  200: Array<OpenapiHealthRecord>
}

export type GetApiHealthRecordResponse =
  GetApiHealthRecordResponses[keyof GetApiHealthRecordResponses]

export type PostApiHealthRecordData = {
  body: OpenapiHealthRecord
  path?: never
  query?: never
  url: "/api/health-record"
}

export type PostApiHealthRecordErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiHealthRecordResponses = {
  201: OpenapiHealthRecord
}

export type PostApiHealthRecordResponse =
  PostApiHealthRecordResponses[keyof PostApiHealthRecordResponses]

export type GetApiHealthRecordCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/health-record/count"
}

export type GetApiHealthRecordCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiHealthRecordCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiHealthRecordCountResponse =
  GetApiHealthRecordCountResponses[keyof GetApiHealthRecordCountResponses]

export type DeleteApiHealthRecordByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/health-record/{id}"
}

export type DeleteApiHealthRecordByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiHealthRecordByIdResponses = {
  204: void
}

export type DeleteApiHealthRecordByIdResponse =
  DeleteApiHealthRecordByIdResponses[keyof DeleteApiHealthRecordByIdResponses]

export type GetApiHealthRecordByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/health-record/{id}"
}

export type GetApiHealthRecordByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiHealthRecordByIdResponses = {
  /**
   * OK
   */
  200: OpenapiHealthRecord
}

export type GetApiHealthRecordByIdResponse =
  GetApiHealthRecordByIdResponses[keyof GetApiHealthRecordByIdResponses]

export type PutApiHealthRecordByIdData = {
  body: OpenapiHealthRecord
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/health-record/{id}"
}

export type PutApiHealthRecordByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiHealthRecordByIdResponses = {
  201: OpenapiHealthRecord
}

export type PutApiHealthRecordByIdResponse =
  PutApiHealthRecordByIdResponses[keyof PutApiHealthRecordByIdResponses]

export type GetApiPatientData = {
  body?: never
  path?: never
  query?: {
    namedQuery?: string
    nationalId?: string
    page?: number
    phone?: string
    size?: number
    sort?: Array<string>
  }
  url: "/api/patient"
}

export type GetApiPatientErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiPatientResponses = {
  /**
   * OK
   */
  200: Array<OpenapiPatient>
}

export type GetApiPatientResponse =
  GetApiPatientResponses[keyof GetApiPatientResponses]

export type PostApiPatientData = {
  body: OpenapiPatient
  path?: never
  query?: never
  url: "/api/patient"
}

export type PostApiPatientErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiPatientResponses = {
  201: OpenapiPatient
}

export type PostApiPatientResponse =
  PostApiPatientResponses[keyof PostApiPatientResponses]

export type GetApiPatientCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/patient/count"
}

export type GetApiPatientCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiPatientCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiPatientCountResponse =
  GetApiPatientCountResponses[keyof GetApiPatientCountResponses]

export type DeleteApiPatientByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/patient/{id}"
}

export type DeleteApiPatientByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiPatientByIdResponses = {
  204: void
}

export type DeleteApiPatientByIdResponse =
  DeleteApiPatientByIdResponses[keyof DeleteApiPatientByIdResponses]

export type GetApiPatientByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/patient/{id}"
}

export type GetApiPatientByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiPatientByIdResponses = {
  /**
   * OK
   */
  200: OpenapiPatient
}

export type GetApiPatientByIdResponse =
  GetApiPatientByIdResponses[keyof GetApiPatientByIdResponses]

export type PutApiPatientByIdData = {
  body: OpenapiPatient
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/patient/{id}"
}

export type PutApiPatientByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiPatientByIdResponses = {
  201: OpenapiPatient
}

export type PutApiPatientByIdResponse =
  PutApiPatientByIdResponses[keyof PutApiPatientByIdResponses]

export type GetApiPrescriptionData = {
  body?: never
  path?: never
  query?: {
    instructions?: string
    medicationDetails?: string
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/prescription"
}

export type GetApiPrescriptionErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiPrescriptionResponses = {
  /**
   * OK
   */
  200: Array<OpenapiPrescription>
}

export type GetApiPrescriptionResponse =
  GetApiPrescriptionResponses[keyof GetApiPrescriptionResponses]

export type PostApiPrescriptionData = {
  body: OpenapiPrescription
  path?: never
  query?: never
  url: "/api/prescription"
}

export type PostApiPrescriptionErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiPrescriptionResponses = {
  201: OpenapiPrescription
}

export type PostApiPrescriptionResponse =
  PostApiPrescriptionResponses[keyof PostApiPrescriptionResponses]

export type GetApiPrescriptionCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/prescription/count"
}

export type GetApiPrescriptionCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiPrescriptionCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiPrescriptionCountResponse =
  GetApiPrescriptionCountResponses[keyof GetApiPrescriptionCountResponses]

export type DeleteApiPrescriptionByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/prescription/{id}"
}

export type DeleteApiPrescriptionByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiPrescriptionByIdResponses = {
  204: void
}

export type DeleteApiPrescriptionByIdResponse =
  DeleteApiPrescriptionByIdResponses[keyof DeleteApiPrescriptionByIdResponses]

export type GetApiPrescriptionByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/prescription/{id}"
}

export type GetApiPrescriptionByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiPrescriptionByIdResponses = {
  /**
   * OK
   */
  200: OpenapiPrescription
}

export type GetApiPrescriptionByIdResponse =
  GetApiPrescriptionByIdResponses[keyof GetApiPrescriptionByIdResponses]

export type PutApiPrescriptionByIdData = {
  body: OpenapiPrescription
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/prescription/{id}"
}

export type PutApiPrescriptionByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiPrescriptionByIdResponses = {
  201: OpenapiPrescription
}

export type PutApiPrescriptionByIdResponse =
  PutApiPrescriptionByIdResponses[keyof PutApiPrescriptionByIdResponses]

export type GetApiInsuranceInvoiceData = {
  body?: never
  path?: never
  query?: {
    namedQuery?: string
    page?: number
    paymentMethod?: string
    size?: number
    sort?: Array<string>
  }
  url: "/api/insurance/invoice"
}

export type GetApiInsuranceInvoiceErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiInsuranceInvoiceResponses = {
  /**
   * OK
   */
  200: Array<OpenapiInvoice>
}

export type GetApiInsuranceInvoiceResponse =
  GetApiInsuranceInvoiceResponses[keyof GetApiInsuranceInvoiceResponses]

export type PostApiInsuranceInvoiceData = {
  body: OpenapiInvoice
  path?: never
  query?: never
  url: "/api/insurance/invoice"
}

export type PostApiInsuranceInvoiceErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiInsuranceInvoiceResponses = {
  201: OpenapiInvoice
}

export type PostApiInsuranceInvoiceResponse =
  PostApiInsuranceInvoiceResponses[keyof PostApiInsuranceInvoiceResponses]

export type GetApiInsuranceInvoiceCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/insurance/invoice/count"
}

export type GetApiInsuranceInvoiceCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiInsuranceInvoiceCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiInsuranceInvoiceCountResponse =
  GetApiInsuranceInvoiceCountResponses[keyof GetApiInsuranceInvoiceCountResponses]

export type DeleteApiInsuranceInvoiceByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/insurance/invoice/{id}"
}

export type DeleteApiInsuranceInvoiceByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiInsuranceInvoiceByIdResponses = {
  204: void
}

export type DeleteApiInsuranceInvoiceByIdResponse =
  DeleteApiInsuranceInvoiceByIdResponses[keyof DeleteApiInsuranceInvoiceByIdResponses]

export type GetApiInsuranceInvoiceByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/insurance/invoice/{id}"
}

export type GetApiInsuranceInvoiceByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiInsuranceInvoiceByIdResponses = {
  /**
   * OK
   */
  200: OpenapiInvoice
}

export type GetApiInsuranceInvoiceByIdResponse =
  GetApiInsuranceInvoiceByIdResponses[keyof GetApiInsuranceInvoiceByIdResponses]

export type PutApiInsuranceInvoiceByIdData = {
  body: OpenapiInvoice
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/insurance/invoice/{id}"
}

export type PutApiInsuranceInvoiceByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiInsuranceInvoiceByIdResponses = {
  201: OpenapiInvoice
}

export type PutApiInsuranceInvoiceByIdResponse =
  PutApiInsuranceInvoiceByIdResponses[keyof PutApiInsuranceInvoiceByIdResponses]

export type GetApiInsuranceProviderData = {
  body?: never
  path?: never
  query?: {
    coverageDetails?: string
    name?: string
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/insurance/provider"
}

export type GetApiInsuranceProviderErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiInsuranceProviderResponses = {
  /**
   * OK
   */
  200: Array<OpenapiInsuranceProvider>
}

export type GetApiInsuranceProviderResponse =
  GetApiInsuranceProviderResponses[keyof GetApiInsuranceProviderResponses]

export type PostApiInsuranceProviderData = {
  body: OpenapiInsuranceProvider
  path?: never
  query?: never
  url: "/api/insurance/provider"
}

export type PostApiInsuranceProviderErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiInsuranceProviderResponses = {
  201: OpenapiInsuranceProvider
}

export type PostApiInsuranceProviderResponse =
  PostApiInsuranceProviderResponses[keyof PostApiInsuranceProviderResponses]

export type GetApiInsuranceProviderCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/insurance/provider/count"
}

export type GetApiInsuranceProviderCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiInsuranceProviderCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiInsuranceProviderCountResponse =
  GetApiInsuranceProviderCountResponses[keyof GetApiInsuranceProviderCountResponses]

export type DeleteApiInsuranceProviderByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/insurance/provider/{id}"
}

export type DeleteApiInsuranceProviderByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiInsuranceProviderByIdResponses = {
  204: void
}

export type DeleteApiInsuranceProviderByIdResponse =
  DeleteApiInsuranceProviderByIdResponses[keyof DeleteApiInsuranceProviderByIdResponses]

export type GetApiInsuranceProviderByIdData = {
  body?: never
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/insurance/provider/{id}"
}

export type GetApiInsuranceProviderByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiInsuranceProviderByIdResponses = {
  /**
   * OK
   */
  200: OpenapiInsuranceProvider
}

export type GetApiInsuranceProviderByIdResponse =
  GetApiInsuranceProviderByIdResponses[keyof GetApiInsuranceProviderByIdResponses]

export type PutApiInsuranceProviderByIdData = {
  body: OpenapiInsuranceProvider
  path: {
    id: OpenapiUuid
  }
  query?: never
  url: "/api/insurance/provider/{id}"
}

export type PutApiInsuranceProviderByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiInsuranceProviderByIdResponses = {
  201: OpenapiInsuranceProvider
}

export type PutApiInsuranceProviderByIdResponse =
  PutApiInsuranceProviderByIdResponses[keyof PutApiInsuranceProviderByIdResponses]
