// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://localhost:8080" | (string & {})
}

export type Appointment = {
  id: Uuid
  patient: Patient
  doctor: Doctor
  facility: Facility
  scheduledDate: LocalDateTime
  status?: AppointmentStatus
}

export type AppointmentStatus = "PENDING" | "COMPLETED" | "CANCELED"

export type Doctor = {
  id: Uuid
  medicalLicense: string
  firstName: string
  lastName: string
  specialties?: Array<Specialty>
  facilities?: Array<Facility>
}

export type Facility = {
  id: Uuid
  name: string
  address: string
}

/**
 * HTTP Problem Response according to RFC9457 and RFC7807
 */
export type HttpProblem = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status?: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance?: string
  [key: string]: unknown
}

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export type HttpValidationProblem = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status?: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance?: string
  /**
   * List of validation constraint violations that occurred
   */
  violations?: Array<Violation>
  [key: string]: unknown
}

export type LocalDateTime = string

export type Patient = {
  id: Uuid
  nationalId: string
  phone: string
}

export type Specialty = {
  id: Uuid
  name: string
}

export type Uuid = string

/**
 * Validation constraint violation details
 */
export type Violation = {
  /**
   * The field for which the validation failed
   */
  field?: string
  /**
   * Part of the http request where the validation error occurred such as query, path, header, form, body
   */
  in?: string
  /**
   * Description of the validation error
   */
  message?: string
}

export type GetApiAppointmentData = {
  body?: never
  path?: never
  query?: {
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/appointment"
}

export type GetApiAppointmentErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiAppointmentResponses = {
  /**
   * OK
   */
  200: Array<Appointment>
}

export type GetApiAppointmentResponse =
  GetApiAppointmentResponses[keyof GetApiAppointmentResponses]

export type PostApiAppointmentData = {
  body: Appointment
  path?: never
  query?: never
  url: "/api/appointment"
}

export type PostApiAppointmentErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiAppointmentResponses = {
  201: Appointment
}

export type PostApiAppointmentResponse =
  PostApiAppointmentResponses[keyof PostApiAppointmentResponses]

export type GetApiAppointmentCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/appointment/count"
}

export type GetApiAppointmentCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiAppointmentCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiAppointmentCountResponse =
  GetApiAppointmentCountResponses[keyof GetApiAppointmentCountResponses]

export type DeleteApiAppointmentByIdData = {
  body?: never
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/appointment/{id}"
}

export type DeleteApiAppointmentByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiAppointmentByIdResponses = {
  204: void
}

export type DeleteApiAppointmentByIdResponse =
  DeleteApiAppointmentByIdResponses[keyof DeleteApiAppointmentByIdResponses]

export type GetApiAppointmentByIdData = {
  body?: never
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/appointment/{id}"
}

export type GetApiAppointmentByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiAppointmentByIdResponses = {
  /**
   * OK
   */
  200: Appointment
}

export type GetApiAppointmentByIdResponse =
  GetApiAppointmentByIdResponses[keyof GetApiAppointmentByIdResponses]

export type PutApiAppointmentByIdData = {
  body: Appointment
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/appointment/{id}"
}

export type PutApiAppointmentByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiAppointmentByIdResponses = {
  201: Appointment
}

export type PutApiAppointmentByIdResponse =
  PutApiAppointmentByIdResponses[keyof PutApiAppointmentByIdResponses]

export type GetApiDoctorData = {
  body?: never
  path?: never
  query?: {
    firstName?: string
    lastName?: string
    medicalLicense?: string
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/doctor"
}

export type GetApiDoctorErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiDoctorResponses = {
  /**
   * OK
   */
  200: Array<Doctor>
}

export type GetApiDoctorResponse =
  GetApiDoctorResponses[keyof GetApiDoctorResponses]

export type PostApiDoctorData = {
  body: Doctor
  path?: never
  query?: never
  url: "/api/doctor"
}

export type PostApiDoctorErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiDoctorResponses = {
  201: Doctor
}

export type PostApiDoctorResponse =
  PostApiDoctorResponses[keyof PostApiDoctorResponses]

export type GetApiDoctorCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/doctor/count"
}

export type GetApiDoctorCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiDoctorCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiDoctorCountResponse =
  GetApiDoctorCountResponses[keyof GetApiDoctorCountResponses]

export type DeleteApiDoctorByIdData = {
  body?: never
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/doctor/{id}"
}

export type DeleteApiDoctorByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiDoctorByIdResponses = {
  204: void
}

export type DeleteApiDoctorByIdResponse =
  DeleteApiDoctorByIdResponses[keyof DeleteApiDoctorByIdResponses]

export type GetApiDoctorByIdData = {
  body?: never
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/doctor/{id}"
}

export type GetApiDoctorByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiDoctorByIdResponses = {
  /**
   * OK
   */
  200: Doctor
}

export type GetApiDoctorByIdResponse =
  GetApiDoctorByIdResponses[keyof GetApiDoctorByIdResponses]

export type PutApiDoctorByIdData = {
  body: Doctor
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/doctor/{id}"
}

export type PutApiDoctorByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiDoctorByIdResponses = {
  201: Doctor
}

export type PutApiDoctorByIdResponse =
  PutApiDoctorByIdResponses[keyof PutApiDoctorByIdResponses]

export type GetApiFacilityData = {
  body?: never
  path?: never
  query?: {
    address?: string
    name?: string
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/facility"
}

export type GetApiFacilityErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiFacilityResponses = {
  /**
   * OK
   */
  200: Array<Facility>
}

export type GetApiFacilityResponse =
  GetApiFacilityResponses[keyof GetApiFacilityResponses]

export type PostApiFacilityData = {
  body: Facility
  path?: never
  query?: never
  url: "/api/facility"
}

export type PostApiFacilityErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiFacilityResponses = {
  201: Facility
}

export type PostApiFacilityResponse =
  PostApiFacilityResponses[keyof PostApiFacilityResponses]

export type GetApiFacilityCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/facility/count"
}

export type GetApiFacilityCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiFacilityCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiFacilityCountResponse =
  GetApiFacilityCountResponses[keyof GetApiFacilityCountResponses]

export type DeleteApiFacilityByIdData = {
  body?: never
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/facility/{id}"
}

export type DeleteApiFacilityByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiFacilityByIdResponses = {
  204: void
}

export type DeleteApiFacilityByIdResponse =
  DeleteApiFacilityByIdResponses[keyof DeleteApiFacilityByIdResponses]

export type GetApiFacilityByIdData = {
  body?: never
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/facility/{id}"
}

export type GetApiFacilityByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiFacilityByIdResponses = {
  /**
   * OK
   */
  200: Facility
}

export type GetApiFacilityByIdResponse =
  GetApiFacilityByIdResponses[keyof GetApiFacilityByIdResponses]

export type PutApiFacilityByIdData = {
  body: Facility
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/facility/{id}"
}

export type PutApiFacilityByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiFacilityByIdResponses = {
  201: Facility
}

export type PutApiFacilityByIdResponse =
  PutApiFacilityByIdResponses[keyof PutApiFacilityByIdResponses]

export type GetApiSpecialtyData = {
  body?: never
  path?: never
  query?: {
    name?: string
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/specialty"
}

export type GetApiSpecialtyErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiSpecialtyResponses = {
  /**
   * OK
   */
  200: Array<Specialty>
}

export type GetApiSpecialtyResponse =
  GetApiSpecialtyResponses[keyof GetApiSpecialtyResponses]

export type PostApiSpecialtyData = {
  body: Specialty
  path?: never
  query?: never
  url: "/api/specialty"
}

export type PostApiSpecialtyErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiSpecialtyResponses = {
  201: Specialty
}

export type PostApiSpecialtyResponse =
  PostApiSpecialtyResponses[keyof PostApiSpecialtyResponses]

export type GetApiSpecialtyCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/specialty/count"
}

export type GetApiSpecialtyCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiSpecialtyCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiSpecialtyCountResponse =
  GetApiSpecialtyCountResponses[keyof GetApiSpecialtyCountResponses]

export type DeleteApiSpecialtyByIdData = {
  body?: never
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/specialty/{id}"
}

export type DeleteApiSpecialtyByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiSpecialtyByIdResponses = {
  204: void
}

export type DeleteApiSpecialtyByIdResponse =
  DeleteApiSpecialtyByIdResponses[keyof DeleteApiSpecialtyByIdResponses]

export type GetApiSpecialtyByIdData = {
  body?: never
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/specialty/{id}"
}

export type GetApiSpecialtyByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiSpecialtyByIdResponses = {
  /**
   * OK
   */
  200: Specialty
}

export type GetApiSpecialtyByIdResponse =
  GetApiSpecialtyByIdResponses[keyof GetApiSpecialtyByIdResponses]

export type PutApiSpecialtyByIdData = {
  body: Specialty
  path: {
    id: Uuid
  }
  query?: never
  url: "/api/specialty/{id}"
}

export type PutApiSpecialtyByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiSpecialtyByIdResponses = {
  201: Specialty
}

export type PutApiSpecialtyByIdResponse =
  PutApiSpecialtyByIdResponses[keyof PutApiSpecialtyByIdResponses]
