// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
  DeleteApiAppointmentByIdData,
  DeleteApiAppointmentByIdErrors,
  DeleteApiAppointmentByIdResponses,
  GetApiAppointmentByIdData,
  GetApiAppointmentByIdErrors,
  GetApiAppointmentByIdResponses,
  GetApiAppointmentCountData,
  GetApiAppointmentCountErrors,
  GetApiAppointmentCountResponses,
  GetApiAppointmentData,
  GetApiAppointmentErrors,
  GetApiAppointmentResponses,
  PostApiAppointmentData,
  PostApiAppointmentErrors,
  PostApiAppointmentResponses,
  PutApiAppointmentByIdData,
  PutApiAppointmentByIdErrors,
  PutApiAppointmentByIdResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const getApiAppointment = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAppointmentData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiAppointmentResponses,
    GetApiAppointmentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment",
    ...options,
  })

export const postApiAppointment = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAppointmentData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAppointmentResponses,
    PostApiAppointmentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiAppointmentCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAppointmentCountData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiAppointmentCountResponses,
    GetApiAppointmentCountErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment/count",
    ...options,
  })

export const deleteApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiAppointmentByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiAppointmentByIdResponses,
    DeleteApiAppointmentByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment/{id}",
    ...options,
  })

export const getApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAppointmentByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiAppointmentByIdResponses,
    GetApiAppointmentByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment/{id}",
    ...options,
  })

export const putApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiAppointmentByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiAppointmentByIdResponses,
    PutApiAppointmentByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/appointment/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
