// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {})
}

export type Appointment = {
  id?: Uuid
  patient?: Patient
  doctor?: Doctor
  facility?: Facility
  scheduledDate?: LocalDateTime
  status?: AppointmentStatus
}

export type AppointmentStatus = "PENDING" | "COMPLETED" | "CANCELED"

export type Doctor = {
  id: Uuid
  medicalLicense: string
  firstName: string
  lastName: string
  specialties?: Array<Specialty>
  facilities?: Array<Facility>
}

export type Facility = {
  id: Uuid
  name: string
  address: string
}

/**
 * HTTP Problem Response according to RFC9457 and RFC7807
 */
export type HttpProblem = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status?: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance?: string
  [key: string]: unknown
}

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export type HttpValidationProblem = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status?: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance?: string
  /**
   * List of validation constraint violations that occurred
   */
  violations?: Array<Violation>
  [key: string]: unknown
}

export type LocalDateTime = string

export type Patient = {
  id: Uuid
  nationalId: string
  phone: string
}

export type Specialty = {
  id: Uuid
  name: string
}

export type Uuid = string

/**
 * Validation constraint violation details
 */
export type Violation = {
  /**
   * The field for which the validation failed
   */
  field?: string
  /**
   * Part of the http request where the validation error occurred such as query, path, header, form, body
   */
  in?: string
  /**
   * Description of the validation error
   */
  message?: string
}

export type GetApiAppointmentData = {
  body?: never
  path?: never
  query?: {
    namedQuery?: string
    page?: number
    size?: number
    sort?: Array<string>
  }
  url: "/api/appointment"
}

export type GetApiAppointmentErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiAppointmentResponses = {
  /**
   * OK
   */
  200: Array<Appointment>
}

export type GetApiAppointmentResponse =
  GetApiAppointmentResponses[keyof GetApiAppointmentResponses]

export type PostApiAppointmentData = {
  body: Appointment
  path?: never
  query?: never
  url: "/api/appointment"
}

export type PostApiAppointmentErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PostApiAppointmentResponses = {
  201: Appointment
}

export type PostApiAppointmentResponse =
  PostApiAppointmentResponses[keyof PostApiAppointmentResponses]

export type GetApiAppointmentCountData = {
  body?: never
  path?: never
  query?: never
  url: "/api/appointment/count"
}

export type GetApiAppointmentCountErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiAppointmentCountResponses = {
  /**
   * OK
   */
  200: number
}

export type GetApiAppointmentCountResponse =
  GetApiAppointmentCountResponses[keyof GetApiAppointmentCountResponses]

export type DeleteApiAppointmentByIdData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: "/api/appointment/{id}"
}

export type DeleteApiAppointmentByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type DeleteApiAppointmentByIdResponses = {
  204: void
}

export type DeleteApiAppointmentByIdResponse =
  DeleteApiAppointmentByIdResponses[keyof DeleteApiAppointmentByIdResponses]

export type GetApiAppointmentByIdData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: "/api/appointment/{id}"
}

export type GetApiAppointmentByIdErrors = {
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type GetApiAppointmentByIdResponses = {
  /**
   * OK
   */
  200: Appointment
}

export type GetApiAppointmentByIdResponse =
  GetApiAppointmentByIdResponses[keyof GetApiAppointmentByIdResponses]

export type PutApiAppointmentByIdData = {
  body: Appointment
  path: {
    id: number
  }
  query?: never
  url: "/api/appointment/{id}"
}

export type PutApiAppointmentByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Not Authorized
   */
  401: unknown
  /**
   * Not Allowed
   */
  403: unknown
}

export type PutApiAppointmentByIdResponses = {
  201: Appointment
}

export type PutApiAppointmentByIdResponse =
  PutApiAppointmentByIdResponses[keyof PutApiAppointmentByIdResponses]
