# Dev
%dev.quarkus.console.color=true
# App
quarkus.http.port=8082
quarkus.banner.enabled=false
# Hibernate
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
# JWT
mp.jwt.verify.publickey.algorithm=ES256
# Openapi
quarkus.smallrye-openapi.info-title=Healthcare Insurance
quarkus.smallrye-openapi.info-description=API documentation for the Insurance Service of the Healthcare Platform. This service handles insurance management.
quarkus.smallrye-openapi.path=/api/insurance/openapi.json
quarkus.smallrye-openapi.scan-exclude-profiles=internal
quarkus.smallrye-openapi.auto-add-operation-summary=false
# Performance
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true
# SOAP / CXF
quarkus.cxf.path=/ws
quarkus.cxf.endpoint."/invoice".implementor=dev.martindotpy.healthcare.insurance.invoince.adapter.soap.InvoiceSoapService
