// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"
import type { AxiosError } from "axios"

import { client } from "../client.gen"
import {
  deleteApiAppointmentById,
  deleteApiDoctorById,
  deleteApiFacilityById,
  deleteApiSpecialtyById,
  getApiAppointment,
  getApiAppointmentById,
  getApiAppointmentCount,
  getApiDoctor,
  getApiDoctorById,
  getApiDoctorCount,
  getApiFacility,
  getApiFacilityById,
  getApiFacilityCount,
  getApiSpecialty,
  getApiSpecialtyById,
  getApiSpecialtyCount,
  type Options,
  postApiAppointment,
  postApiDoctor,
  postApiFacility,
  postApiSpecialty,
  putApiAppointmentById,
  putApiDoctorById,
  putApiFacilityById,
  putApiSpecialtyById,
} from "../sdk.gen"
import type {
  DeleteApiAppointmentByIdData,
  DeleteApiAppointmentByIdResponse,
  DeleteApiDoctorByIdData,
  DeleteApiDoctorByIdResponse,
  DeleteApiFacilityByIdData,
  DeleteApiFacilityByIdResponse,
  DeleteApiSpecialtyByIdData,
  DeleteApiSpecialtyByIdResponse,
  GetApiAppointmentByIdData,
  GetApiAppointmentByIdResponse,
  GetApiAppointmentCountData,
  GetApiAppointmentCountResponse,
  GetApiAppointmentData,
  GetApiAppointmentResponse,
  GetApiDoctorByIdData,
  GetApiDoctorByIdResponse,
  GetApiDoctorCountData,
  GetApiDoctorCountResponse,
  GetApiDoctorData,
  GetApiDoctorResponse,
  GetApiFacilityByIdData,
  GetApiFacilityByIdResponse,
  GetApiFacilityCountData,
  GetApiFacilityCountResponse,
  GetApiFacilityData,
  GetApiFacilityResponse,
  GetApiSpecialtyByIdData,
  GetApiSpecialtyByIdResponse,
  GetApiSpecialtyCountData,
  GetApiSpecialtyCountResponse,
  GetApiSpecialtyData,
  GetApiSpecialtyResponse,
  PostApiAppointmentData,
  PostApiAppointmentResponse,
  PostApiDoctorData,
  PostApiDoctorResponse,
  PostApiFacilityData,
  PostApiFacilityResponse,
  PostApiSpecialtyData,
  PostApiSpecialtyResponse,
  PutApiAppointmentByIdData,
  PutApiAppointmentByIdResponse,
  PutApiDoctorByIdData,
  PutApiDoctorByIdResponse,
  PutApiFacilityByIdData,
  PutApiFacilityByIdResponse,
  PutApiSpecialtyByIdData,
  PutApiSpecialtyByIdResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getApiAppointmentQueryKey = (
  options?: Options<GetApiAppointmentData>
) => createQueryKey("getApiAppointment", options)

export const getApiAppointmentOptions = (
  options?: Options<GetApiAppointmentData>
) =>
  queryOptions<
    GetApiAppointmentResponse,
    AxiosError<DefaultError>,
    GetApiAppointmentResponse,
    ReturnType<typeof getApiAppointmentQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointment({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const getApiAppointmentInfiniteQueryKey = (
  options?: Options<GetApiAppointmentData>
): QueryKey<Options<GetApiAppointmentData>> =>
  createQueryKey("getApiAppointment", options, true)

export const getApiAppointmentInfiniteOptions = (
  options?: Options<GetApiAppointmentData>
) =>
  infiniteQueryOptions<
    GetApiAppointmentResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiAppointmentResponse>,
    QueryKey<Options<GetApiAppointmentData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiAppointmentData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiAppointmentData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiAppointment({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiAppointmentInfiniteQueryKey(options),
    }
  )

export const postApiAppointmentMutation = (
  options?: Partial<Options<PostApiAppointmentData>>
): UseMutationOptions<
  PostApiAppointmentResponse,
  AxiosError<DefaultError>,
  Options<PostApiAppointmentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAppointmentResponse,
    AxiosError<DefaultError>,
    Options<PostApiAppointmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAppointment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAppointmentCountQueryKey = (
  options?: Options<GetApiAppointmentCountData>
) => createQueryKey("getApiAppointmentCount", options)

export const getApiAppointmentCountOptions = (
  options?: Options<GetApiAppointmentCountData>
) =>
  queryOptions<
    GetApiAppointmentCountResponse,
    AxiosError<DefaultError>,
    GetApiAppointmentCountResponse,
    ReturnType<typeof getApiAppointmentCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointmentCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentCountQueryKey(options),
  })

export const deleteApiAppointmentByIdMutation = (
  options?: Partial<Options<DeleteApiAppointmentByIdData>>
): UseMutationOptions<
  DeleteApiAppointmentByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiAppointmentByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiAppointmentByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiAppointmentByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiAppointmentById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAppointmentByIdQueryKey = (
  options: Options<GetApiAppointmentByIdData>
) => createQueryKey("getApiAppointmentById", options)

export const getApiAppointmentByIdOptions = (
  options: Options<GetApiAppointmentByIdData>
) =>
  queryOptions<
    GetApiAppointmentByIdResponse,
    AxiosError<DefaultError>,
    GetApiAppointmentByIdResponse,
    ReturnType<typeof getApiAppointmentByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointmentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentByIdQueryKey(options),
  })

export const putApiAppointmentByIdMutation = (
  options?: Partial<Options<PutApiAppointmentByIdData>>
): UseMutationOptions<
  PutApiAppointmentByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiAppointmentByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiAppointmentByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiAppointmentByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiAppointmentById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiDoctorQueryKey = (options?: Options<GetApiDoctorData>) =>
  createQueryKey("getApiDoctor", options)

export const getApiDoctorOptions = (options?: Options<GetApiDoctorData>) =>
  queryOptions<
    GetApiDoctorResponse,
    AxiosError<DefaultError>,
    GetApiDoctorResponse,
    ReturnType<typeof getApiDoctorQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDoctor({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDoctorQueryKey(options),
  })

export const getApiDoctorInfiniteQueryKey = (
  options?: Options<GetApiDoctorData>
): QueryKey<Options<GetApiDoctorData>> =>
  createQueryKey("getApiDoctor", options, true)

export const getApiDoctorInfiniteOptions = (
  options?: Options<GetApiDoctorData>
) =>
  infiniteQueryOptions<
    GetApiDoctorResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiDoctorResponse>,
    QueryKey<Options<GetApiDoctorData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiDoctorData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiDoctorData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiDoctor({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiDoctorInfiniteQueryKey(options),
    }
  )

export const postApiDoctorMutation = (
  options?: Partial<Options<PostApiDoctorData>>
): UseMutationOptions<
  PostApiDoctorResponse,
  AxiosError<DefaultError>,
  Options<PostApiDoctorData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiDoctorResponse,
    AxiosError<DefaultError>,
    Options<PostApiDoctorData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiDoctor({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiDoctorCountQueryKey = (
  options?: Options<GetApiDoctorCountData>
) => createQueryKey("getApiDoctorCount", options)

export const getApiDoctorCountOptions = (
  options?: Options<GetApiDoctorCountData>
) =>
  queryOptions<
    GetApiDoctorCountResponse,
    AxiosError<DefaultError>,
    GetApiDoctorCountResponse,
    ReturnType<typeof getApiDoctorCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDoctorCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDoctorCountQueryKey(options),
  })

export const deleteApiDoctorByIdMutation = (
  options?: Partial<Options<DeleteApiDoctorByIdData>>
): UseMutationOptions<
  DeleteApiDoctorByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiDoctorByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiDoctorByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiDoctorByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiDoctorById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiDoctorByIdQueryKey = (
  options: Options<GetApiDoctorByIdData>
) => createQueryKey("getApiDoctorById", options)

export const getApiDoctorByIdOptions = (
  options: Options<GetApiDoctorByIdData>
) =>
  queryOptions<
    GetApiDoctorByIdResponse,
    AxiosError<DefaultError>,
    GetApiDoctorByIdResponse,
    ReturnType<typeof getApiDoctorByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDoctorById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDoctorByIdQueryKey(options),
  })

export const putApiDoctorByIdMutation = (
  options?: Partial<Options<PutApiDoctorByIdData>>
): UseMutationOptions<
  PutApiDoctorByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiDoctorByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiDoctorByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiDoctorByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiDoctorById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiFacilityQueryKey = (options?: Options<GetApiFacilityData>) =>
  createQueryKey("getApiFacility", options)

export const getApiFacilityOptions = (options?: Options<GetApiFacilityData>) =>
  queryOptions<
    GetApiFacilityResponse,
    AxiosError<DefaultError>,
    GetApiFacilityResponse,
    ReturnType<typeof getApiFacilityQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFacility({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiFacilityQueryKey(options),
  })

export const getApiFacilityInfiniteQueryKey = (
  options?: Options<GetApiFacilityData>
): QueryKey<Options<GetApiFacilityData>> =>
  createQueryKey("getApiFacility", options, true)

export const getApiFacilityInfiniteOptions = (
  options?: Options<GetApiFacilityData>
) =>
  infiniteQueryOptions<
    GetApiFacilityResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiFacilityResponse>,
    QueryKey<Options<GetApiFacilityData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiFacilityData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiFacilityData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiFacility({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiFacilityInfiniteQueryKey(options),
    }
  )

export const postApiFacilityMutation = (
  options?: Partial<Options<PostApiFacilityData>>
): UseMutationOptions<
  PostApiFacilityResponse,
  AxiosError<DefaultError>,
  Options<PostApiFacilityData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiFacilityResponse,
    AxiosError<DefaultError>,
    Options<PostApiFacilityData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiFacility({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiFacilityCountQueryKey = (
  options?: Options<GetApiFacilityCountData>
) => createQueryKey("getApiFacilityCount", options)

export const getApiFacilityCountOptions = (
  options?: Options<GetApiFacilityCountData>
) =>
  queryOptions<
    GetApiFacilityCountResponse,
    AxiosError<DefaultError>,
    GetApiFacilityCountResponse,
    ReturnType<typeof getApiFacilityCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFacilityCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiFacilityCountQueryKey(options),
  })

export const deleteApiFacilityByIdMutation = (
  options?: Partial<Options<DeleteApiFacilityByIdData>>
): UseMutationOptions<
  DeleteApiFacilityByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiFacilityByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiFacilityByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiFacilityByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiFacilityById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiFacilityByIdQueryKey = (
  options: Options<GetApiFacilityByIdData>
) => createQueryKey("getApiFacilityById", options)

export const getApiFacilityByIdOptions = (
  options: Options<GetApiFacilityByIdData>
) =>
  queryOptions<
    GetApiFacilityByIdResponse,
    AxiosError<DefaultError>,
    GetApiFacilityByIdResponse,
    ReturnType<typeof getApiFacilityByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFacilityById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiFacilityByIdQueryKey(options),
  })

export const putApiFacilityByIdMutation = (
  options?: Partial<Options<PutApiFacilityByIdData>>
): UseMutationOptions<
  PutApiFacilityByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiFacilityByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiFacilityByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiFacilityByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiFacilityById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiSpecialtyQueryKey = (
  options?: Options<GetApiSpecialtyData>
) => createQueryKey("getApiSpecialty", options)

export const getApiSpecialtyOptions = (
  options?: Options<GetApiSpecialtyData>
) =>
  queryOptions<
    GetApiSpecialtyResponse,
    AxiosError<DefaultError>,
    GetApiSpecialtyResponse,
    ReturnType<typeof getApiSpecialtyQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpecialty({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpecialtyQueryKey(options),
  })

export const getApiSpecialtyInfiniteQueryKey = (
  options?: Options<GetApiSpecialtyData>
): QueryKey<Options<GetApiSpecialtyData>> =>
  createQueryKey("getApiSpecialty", options, true)

export const getApiSpecialtyInfiniteOptions = (
  options?: Options<GetApiSpecialtyData>
) =>
  infiniteQueryOptions<
    GetApiSpecialtyResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiSpecialtyResponse>,
    QueryKey<Options<GetApiSpecialtyData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiSpecialtyData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiSpecialtyData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiSpecialty({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiSpecialtyInfiniteQueryKey(options),
    }
  )

export const postApiSpecialtyMutation = (
  options?: Partial<Options<PostApiSpecialtyData>>
): UseMutationOptions<
  PostApiSpecialtyResponse,
  AxiosError<DefaultError>,
  Options<PostApiSpecialtyData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiSpecialtyResponse,
    AxiosError<DefaultError>,
    Options<PostApiSpecialtyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiSpecialty({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiSpecialtyCountQueryKey = (
  options?: Options<GetApiSpecialtyCountData>
) => createQueryKey("getApiSpecialtyCount", options)

export const getApiSpecialtyCountOptions = (
  options?: Options<GetApiSpecialtyCountData>
) =>
  queryOptions<
    GetApiSpecialtyCountResponse,
    AxiosError<DefaultError>,
    GetApiSpecialtyCountResponse,
    ReturnType<typeof getApiSpecialtyCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpecialtyCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpecialtyCountQueryKey(options),
  })

export const deleteApiSpecialtyByIdMutation = (
  options?: Partial<Options<DeleteApiSpecialtyByIdData>>
): UseMutationOptions<
  DeleteApiSpecialtyByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiSpecialtyByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiSpecialtyByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiSpecialtyByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiSpecialtyById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiSpecialtyByIdQueryKey = (
  options: Options<GetApiSpecialtyByIdData>
) => createQueryKey("getApiSpecialtyById", options)

export const getApiSpecialtyByIdOptions = (
  options: Options<GetApiSpecialtyByIdData>
) =>
  queryOptions<
    GetApiSpecialtyByIdResponse,
    AxiosError<DefaultError>,
    GetApiSpecialtyByIdResponse,
    ReturnType<typeof getApiSpecialtyByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpecialtyById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpecialtyByIdQueryKey(options),
  })

export const putApiSpecialtyByIdMutation = (
  options?: Partial<Options<PutApiSpecialtyByIdData>>
): UseMutationOptions<
  PutApiSpecialtyByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiSpecialtyByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiSpecialtyByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiSpecialtyByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiSpecialtyById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
