// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"
import type { AxiosError } from "axios"

import { client } from "../client.gen"
import {
  deleteApiAppointmentById,
  deleteApiClinicalEpisodeById,
  deleteApiDoctorById,
  deleteApiFacilityById,
  deleteApiHealthRecordById,
  deleteApiInsuranceInvoiceById,
  deleteApiInsuranceProviderById,
  deleteApiPatientById,
  deleteApiPrescriptionById,
  deleteApiSpecialtyById,
  getApiAppointment,
  getApiAppointmentById,
  getApiAppointmentCount,
  getApiClinicalEpisode,
  getApiClinicalEpisodeById,
  getApiClinicalEpisodeCount,
  getApiDoctor,
  getApiDoctorById,
  getApiDoctorCount,
  getApiFacility,
  getApiFacilityById,
  getApiFacilityCount,
  getApiHealthRecord,
  getApiHealthRecordById,
  getApiHealthRecordCount,
  getApiInsuranceInvoice,
  getApiInsuranceInvoiceById,
  getApiInsuranceInvoiceCount,
  getApiInsuranceProvider,
  getApiInsuranceProviderById,
  getApiInsuranceProviderCount,
  getApiPatient,
  getApiPatientById,
  getApiPatientCount,
  getApiPrescription,
  getApiPrescriptionById,
  getApiPrescriptionCount,
  getApiSpecialty,
  getApiSpecialtyById,
  getApiSpecialtyCount,
  type Options,
  postApiAppointment,
  postApiAppointmentValidate,
  postApiClinicalEpisode,
  postApiDoctor,
  postApiFacility,
  postApiHealthRecord,
  postApiInsuranceInvoice,
  postApiInsuranceProvider,
  postApiPatient,
  postApiPrescription,
  postApiSpecialty,
  putApiAppointmentById,
  putApiClinicalEpisodeById,
  putApiDoctorById,
  putApiFacilityById,
  putApiHealthRecordById,
  putApiInsuranceInvoiceById,
  putApiInsuranceProviderById,
  putApiPatientById,
  putApiPrescriptionById,
  putApiSpecialtyById,
} from "../sdk.gen"
import type {
  DeleteApiAppointmentByIdData,
  DeleteApiAppointmentByIdResponse,
  DeleteApiClinicalEpisodeByIdData,
  DeleteApiClinicalEpisodeByIdResponse,
  DeleteApiDoctorByIdData,
  DeleteApiDoctorByIdResponse,
  DeleteApiFacilityByIdData,
  DeleteApiFacilityByIdResponse,
  DeleteApiHealthRecordByIdData,
  DeleteApiHealthRecordByIdResponse,
  DeleteApiInsuranceInvoiceByIdData,
  DeleteApiInsuranceInvoiceByIdResponse,
  DeleteApiInsuranceProviderByIdData,
  DeleteApiInsuranceProviderByIdResponse,
  DeleteApiPatientByIdData,
  DeleteApiPatientByIdResponse,
  DeleteApiPrescriptionByIdData,
  DeleteApiPrescriptionByIdResponse,
  DeleteApiSpecialtyByIdData,
  DeleteApiSpecialtyByIdResponse,
  GetApiAppointmentByIdData,
  GetApiAppointmentByIdResponse,
  GetApiAppointmentCountData,
  GetApiAppointmentCountResponse,
  GetApiAppointmentData,
  GetApiAppointmentResponse,
  GetApiClinicalEpisodeByIdData,
  GetApiClinicalEpisodeByIdResponse,
  GetApiClinicalEpisodeCountData,
  GetApiClinicalEpisodeCountResponse,
  GetApiClinicalEpisodeData,
  GetApiClinicalEpisodeResponse,
  GetApiDoctorByIdData,
  GetApiDoctorByIdResponse,
  GetApiDoctorCountData,
  GetApiDoctorCountResponse,
  GetApiDoctorData,
  GetApiDoctorResponse,
  GetApiFacilityByIdData,
  GetApiFacilityByIdResponse,
  GetApiFacilityCountData,
  GetApiFacilityCountResponse,
  GetApiFacilityData,
  GetApiFacilityResponse,
  GetApiHealthRecordByIdData,
  GetApiHealthRecordByIdResponse,
  GetApiHealthRecordCountData,
  GetApiHealthRecordCountResponse,
  GetApiHealthRecordData,
  GetApiHealthRecordResponse,
  GetApiInsuranceInvoiceByIdData,
  GetApiInsuranceInvoiceByIdResponse,
  GetApiInsuranceInvoiceCountData,
  GetApiInsuranceInvoiceCountResponse,
  GetApiInsuranceInvoiceData,
  GetApiInsuranceInvoiceResponse,
  GetApiInsuranceProviderByIdData,
  GetApiInsuranceProviderByIdResponse,
  GetApiInsuranceProviderCountData,
  GetApiInsuranceProviderCountResponse,
  GetApiInsuranceProviderData,
  GetApiInsuranceProviderResponse,
  GetApiPatientByIdData,
  GetApiPatientByIdResponse,
  GetApiPatientCountData,
  GetApiPatientCountResponse,
  GetApiPatientData,
  GetApiPatientResponse,
  GetApiPrescriptionByIdData,
  GetApiPrescriptionByIdResponse,
  GetApiPrescriptionCountData,
  GetApiPrescriptionCountResponse,
  GetApiPrescriptionData,
  GetApiPrescriptionResponse,
  GetApiSpecialtyByIdData,
  GetApiSpecialtyByIdResponse,
  GetApiSpecialtyCountData,
  GetApiSpecialtyCountResponse,
  GetApiSpecialtyData,
  GetApiSpecialtyResponse,
  PostApiAppointmentData,
  PostApiAppointmentResponse,
  PostApiAppointmentValidateData,
  PostApiAppointmentValidateResponse,
  PostApiClinicalEpisodeData,
  PostApiClinicalEpisodeResponse,
  PostApiDoctorData,
  PostApiDoctorResponse,
  PostApiFacilityData,
  PostApiFacilityResponse,
  PostApiHealthRecordData,
  PostApiHealthRecordResponse,
  PostApiInsuranceInvoiceData,
  PostApiInsuranceInvoiceResponse,
  PostApiInsuranceProviderData,
  PostApiInsuranceProviderResponse,
  PostApiPatientData,
  PostApiPatientResponse,
  PostApiPrescriptionData,
  PostApiPrescriptionResponse,
  PostApiSpecialtyData,
  PostApiSpecialtyResponse,
  PutApiAppointmentByIdData,
  PutApiAppointmentByIdResponse,
  PutApiClinicalEpisodeByIdData,
  PutApiClinicalEpisodeByIdResponse,
  PutApiDoctorByIdData,
  PutApiDoctorByIdResponse,
  PutApiFacilityByIdData,
  PutApiFacilityByIdResponse,
  PutApiHealthRecordByIdData,
  PutApiHealthRecordByIdResponse,
  PutApiInsuranceInvoiceByIdData,
  PutApiInsuranceInvoiceByIdResponse,
  PutApiInsuranceProviderByIdData,
  PutApiInsuranceProviderByIdResponse,
  PutApiPatientByIdData,
  PutApiPatientByIdResponse,
  PutApiPrescriptionByIdData,
  PutApiPrescriptionByIdResponse,
  PutApiSpecialtyByIdData,
  PutApiSpecialtyByIdResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getApiAppointmentQueryKey = (
  options?: Options<GetApiAppointmentData>
) => createQueryKey("getApiAppointment", options)

export const getApiAppointmentOptions = (
  options?: Options<GetApiAppointmentData>
) =>
  queryOptions<
    GetApiAppointmentResponse,
    AxiosError<DefaultError>,
    GetApiAppointmentResponse,
    ReturnType<typeof getApiAppointmentQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointment({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const getApiAppointmentInfiniteQueryKey = (
  options?: Options<GetApiAppointmentData>
): QueryKey<Options<GetApiAppointmentData>> =>
  createQueryKey("getApiAppointment", options, true)

export const getApiAppointmentInfiniteOptions = (
  options?: Options<GetApiAppointmentData>
) =>
  infiniteQueryOptions<
    GetApiAppointmentResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiAppointmentResponse>,
    QueryKey<Options<GetApiAppointmentData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiAppointmentData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiAppointmentData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiAppointment({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiAppointmentInfiniteQueryKey(options),
    }
  )

export const postApiAppointmentMutation = (
  options?: Partial<Options<PostApiAppointmentData>>
): UseMutationOptions<
  PostApiAppointmentResponse,
  AxiosError<DefaultError>,
  Options<PostApiAppointmentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAppointmentResponse,
    AxiosError<DefaultError>,
    Options<PostApiAppointmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAppointment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAppointmentCountQueryKey = (
  options?: Options<GetApiAppointmentCountData>
) => createQueryKey("getApiAppointmentCount", options)

export const getApiAppointmentCountOptions = (
  options?: Options<GetApiAppointmentCountData>
) =>
  queryOptions<
    GetApiAppointmentCountResponse,
    AxiosError<DefaultError>,
    GetApiAppointmentCountResponse,
    ReturnType<typeof getApiAppointmentCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointmentCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentCountQueryKey(options),
  })

/**
 * Validate appointment scheduling rules
 */
export const postApiAppointmentValidateMutation = (
  options?: Partial<Options<PostApiAppointmentValidateData>>
): UseMutationOptions<
  PostApiAppointmentValidateResponse,
  AxiosError<DefaultError>,
  Options<PostApiAppointmentValidateData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAppointmentValidateResponse,
    AxiosError<DefaultError>,
    Options<PostApiAppointmentValidateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAppointmentValidate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const deleteApiAppointmentByIdMutation = (
  options?: Partial<Options<DeleteApiAppointmentByIdData>>
): UseMutationOptions<
  DeleteApiAppointmentByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiAppointmentByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiAppointmentByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiAppointmentByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiAppointmentById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAppointmentByIdQueryKey = (
  options: Options<GetApiAppointmentByIdData>
) => createQueryKey("getApiAppointmentById", options)

export const getApiAppointmentByIdOptions = (
  options: Options<GetApiAppointmentByIdData>
) =>
  queryOptions<
    GetApiAppointmentByIdResponse,
    AxiosError<DefaultError>,
    GetApiAppointmentByIdResponse,
    ReturnType<typeof getApiAppointmentByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointmentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentByIdQueryKey(options),
  })

export const putApiAppointmentByIdMutation = (
  options?: Partial<Options<PutApiAppointmentByIdData>>
): UseMutationOptions<
  PutApiAppointmentByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiAppointmentByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiAppointmentByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiAppointmentByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiAppointmentById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiDoctorQueryKey = (options?: Options<GetApiDoctorData>) =>
  createQueryKey("getApiDoctor", options)

export const getApiDoctorOptions = (options?: Options<GetApiDoctorData>) =>
  queryOptions<
    GetApiDoctorResponse,
    AxiosError<DefaultError>,
    GetApiDoctorResponse,
    ReturnType<typeof getApiDoctorQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDoctor({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDoctorQueryKey(options),
  })

export const getApiDoctorInfiniteQueryKey = (
  options?: Options<GetApiDoctorData>
): QueryKey<Options<GetApiDoctorData>> =>
  createQueryKey("getApiDoctor", options, true)

export const getApiDoctorInfiniteOptions = (
  options?: Options<GetApiDoctorData>
) =>
  infiniteQueryOptions<
    GetApiDoctorResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiDoctorResponse>,
    QueryKey<Options<GetApiDoctorData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiDoctorData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiDoctorData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiDoctor({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiDoctorInfiniteQueryKey(options),
    }
  )

export const postApiDoctorMutation = (
  options?: Partial<Options<PostApiDoctorData>>
): UseMutationOptions<
  PostApiDoctorResponse,
  AxiosError<DefaultError>,
  Options<PostApiDoctorData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiDoctorResponse,
    AxiosError<DefaultError>,
    Options<PostApiDoctorData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiDoctor({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiDoctorCountQueryKey = (
  options?: Options<GetApiDoctorCountData>
) => createQueryKey("getApiDoctorCount", options)

export const getApiDoctorCountOptions = (
  options?: Options<GetApiDoctorCountData>
) =>
  queryOptions<
    GetApiDoctorCountResponse,
    AxiosError<DefaultError>,
    GetApiDoctorCountResponse,
    ReturnType<typeof getApiDoctorCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDoctorCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDoctorCountQueryKey(options),
  })

export const deleteApiDoctorByIdMutation = (
  options?: Partial<Options<DeleteApiDoctorByIdData>>
): UseMutationOptions<
  DeleteApiDoctorByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiDoctorByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiDoctorByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiDoctorByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiDoctorById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiDoctorByIdQueryKey = (
  options: Options<GetApiDoctorByIdData>
) => createQueryKey("getApiDoctorById", options)

export const getApiDoctorByIdOptions = (
  options: Options<GetApiDoctorByIdData>
) =>
  queryOptions<
    GetApiDoctorByIdResponse,
    AxiosError<DefaultError>,
    GetApiDoctorByIdResponse,
    ReturnType<typeof getApiDoctorByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDoctorById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDoctorByIdQueryKey(options),
  })

export const putApiDoctorByIdMutation = (
  options?: Partial<Options<PutApiDoctorByIdData>>
): UseMutationOptions<
  PutApiDoctorByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiDoctorByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiDoctorByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiDoctorByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiDoctorById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiFacilityQueryKey = (options?: Options<GetApiFacilityData>) =>
  createQueryKey("getApiFacility", options)

export const getApiFacilityOptions = (options?: Options<GetApiFacilityData>) =>
  queryOptions<
    GetApiFacilityResponse,
    AxiosError<DefaultError>,
    GetApiFacilityResponse,
    ReturnType<typeof getApiFacilityQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFacility({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiFacilityQueryKey(options),
  })

export const getApiFacilityInfiniteQueryKey = (
  options?: Options<GetApiFacilityData>
): QueryKey<Options<GetApiFacilityData>> =>
  createQueryKey("getApiFacility", options, true)

export const getApiFacilityInfiniteOptions = (
  options?: Options<GetApiFacilityData>
) =>
  infiniteQueryOptions<
    GetApiFacilityResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiFacilityResponse>,
    QueryKey<Options<GetApiFacilityData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiFacilityData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiFacilityData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiFacility({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiFacilityInfiniteQueryKey(options),
    }
  )

export const postApiFacilityMutation = (
  options?: Partial<Options<PostApiFacilityData>>
): UseMutationOptions<
  PostApiFacilityResponse,
  AxiosError<DefaultError>,
  Options<PostApiFacilityData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiFacilityResponse,
    AxiosError<DefaultError>,
    Options<PostApiFacilityData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiFacility({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiFacilityCountQueryKey = (
  options?: Options<GetApiFacilityCountData>
) => createQueryKey("getApiFacilityCount", options)

export const getApiFacilityCountOptions = (
  options?: Options<GetApiFacilityCountData>
) =>
  queryOptions<
    GetApiFacilityCountResponse,
    AxiosError<DefaultError>,
    GetApiFacilityCountResponse,
    ReturnType<typeof getApiFacilityCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFacilityCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiFacilityCountQueryKey(options),
  })

export const deleteApiFacilityByIdMutation = (
  options?: Partial<Options<DeleteApiFacilityByIdData>>
): UseMutationOptions<
  DeleteApiFacilityByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiFacilityByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiFacilityByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiFacilityByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiFacilityById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiFacilityByIdQueryKey = (
  options: Options<GetApiFacilityByIdData>
) => createQueryKey("getApiFacilityById", options)

export const getApiFacilityByIdOptions = (
  options: Options<GetApiFacilityByIdData>
) =>
  queryOptions<
    GetApiFacilityByIdResponse,
    AxiosError<DefaultError>,
    GetApiFacilityByIdResponse,
    ReturnType<typeof getApiFacilityByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFacilityById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiFacilityByIdQueryKey(options),
  })

export const putApiFacilityByIdMutation = (
  options?: Partial<Options<PutApiFacilityByIdData>>
): UseMutationOptions<
  PutApiFacilityByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiFacilityByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiFacilityByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiFacilityByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiFacilityById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiSpecialtyQueryKey = (
  options?: Options<GetApiSpecialtyData>
) => createQueryKey("getApiSpecialty", options)

export const getApiSpecialtyOptions = (
  options?: Options<GetApiSpecialtyData>
) =>
  queryOptions<
    GetApiSpecialtyResponse,
    AxiosError<DefaultError>,
    GetApiSpecialtyResponse,
    ReturnType<typeof getApiSpecialtyQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpecialty({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpecialtyQueryKey(options),
  })

export const getApiSpecialtyInfiniteQueryKey = (
  options?: Options<GetApiSpecialtyData>
): QueryKey<Options<GetApiSpecialtyData>> =>
  createQueryKey("getApiSpecialty", options, true)

export const getApiSpecialtyInfiniteOptions = (
  options?: Options<GetApiSpecialtyData>
) =>
  infiniteQueryOptions<
    GetApiSpecialtyResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiSpecialtyResponse>,
    QueryKey<Options<GetApiSpecialtyData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiSpecialtyData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiSpecialtyData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiSpecialty({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiSpecialtyInfiniteQueryKey(options),
    }
  )

export const postApiSpecialtyMutation = (
  options?: Partial<Options<PostApiSpecialtyData>>
): UseMutationOptions<
  PostApiSpecialtyResponse,
  AxiosError<DefaultError>,
  Options<PostApiSpecialtyData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiSpecialtyResponse,
    AxiosError<DefaultError>,
    Options<PostApiSpecialtyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiSpecialty({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiSpecialtyCountQueryKey = (
  options?: Options<GetApiSpecialtyCountData>
) => createQueryKey("getApiSpecialtyCount", options)

export const getApiSpecialtyCountOptions = (
  options?: Options<GetApiSpecialtyCountData>
) =>
  queryOptions<
    GetApiSpecialtyCountResponse,
    AxiosError<DefaultError>,
    GetApiSpecialtyCountResponse,
    ReturnType<typeof getApiSpecialtyCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpecialtyCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpecialtyCountQueryKey(options),
  })

export const deleteApiSpecialtyByIdMutation = (
  options?: Partial<Options<DeleteApiSpecialtyByIdData>>
): UseMutationOptions<
  DeleteApiSpecialtyByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiSpecialtyByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiSpecialtyByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiSpecialtyByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiSpecialtyById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiSpecialtyByIdQueryKey = (
  options: Options<GetApiSpecialtyByIdData>
) => createQueryKey("getApiSpecialtyById", options)

export const getApiSpecialtyByIdOptions = (
  options: Options<GetApiSpecialtyByIdData>
) =>
  queryOptions<
    GetApiSpecialtyByIdResponse,
    AxiosError<DefaultError>,
    GetApiSpecialtyByIdResponse,
    ReturnType<typeof getApiSpecialtyByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpecialtyById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpecialtyByIdQueryKey(options),
  })

export const putApiSpecialtyByIdMutation = (
  options?: Partial<Options<PutApiSpecialtyByIdData>>
): UseMutationOptions<
  PutApiSpecialtyByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiSpecialtyByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiSpecialtyByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiSpecialtyByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiSpecialtyById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiClinicalEpisodeQueryKey = (
  options?: Options<GetApiClinicalEpisodeData>
) => createQueryKey("getApiClinicalEpisode", options)

export const getApiClinicalEpisodeOptions = (
  options?: Options<GetApiClinicalEpisodeData>
) =>
  queryOptions<
    GetApiClinicalEpisodeResponse,
    AxiosError<DefaultError>,
    GetApiClinicalEpisodeResponse,
    ReturnType<typeof getApiClinicalEpisodeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiClinicalEpisode({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiClinicalEpisodeQueryKey(options),
  })

export const getApiClinicalEpisodeInfiniteQueryKey = (
  options?: Options<GetApiClinicalEpisodeData>
): QueryKey<Options<GetApiClinicalEpisodeData>> =>
  createQueryKey("getApiClinicalEpisode", options, true)

export const getApiClinicalEpisodeInfiniteOptions = (
  options?: Options<GetApiClinicalEpisodeData>
) =>
  infiniteQueryOptions<
    GetApiClinicalEpisodeResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiClinicalEpisodeResponse>,
    QueryKey<Options<GetApiClinicalEpisodeData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiClinicalEpisodeData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiClinicalEpisodeData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiClinicalEpisode({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiClinicalEpisodeInfiniteQueryKey(options),
    }
  )

export const postApiClinicalEpisodeMutation = (
  options?: Partial<Options<PostApiClinicalEpisodeData>>
): UseMutationOptions<
  PostApiClinicalEpisodeResponse,
  AxiosError<DefaultError>,
  Options<PostApiClinicalEpisodeData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiClinicalEpisodeResponse,
    AxiosError<DefaultError>,
    Options<PostApiClinicalEpisodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiClinicalEpisode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiClinicalEpisodeCountQueryKey = (
  options?: Options<GetApiClinicalEpisodeCountData>
) => createQueryKey("getApiClinicalEpisodeCount", options)

export const getApiClinicalEpisodeCountOptions = (
  options?: Options<GetApiClinicalEpisodeCountData>
) =>
  queryOptions<
    GetApiClinicalEpisodeCountResponse,
    AxiosError<DefaultError>,
    GetApiClinicalEpisodeCountResponse,
    ReturnType<typeof getApiClinicalEpisodeCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiClinicalEpisodeCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiClinicalEpisodeCountQueryKey(options),
  })

export const deleteApiClinicalEpisodeByIdMutation = (
  options?: Partial<Options<DeleteApiClinicalEpisodeByIdData>>
): UseMutationOptions<
  DeleteApiClinicalEpisodeByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiClinicalEpisodeByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiClinicalEpisodeByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiClinicalEpisodeByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiClinicalEpisodeById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiClinicalEpisodeByIdQueryKey = (
  options: Options<GetApiClinicalEpisodeByIdData>
) => createQueryKey("getApiClinicalEpisodeById", options)

export const getApiClinicalEpisodeByIdOptions = (
  options: Options<GetApiClinicalEpisodeByIdData>
) =>
  queryOptions<
    GetApiClinicalEpisodeByIdResponse,
    AxiosError<DefaultError>,
    GetApiClinicalEpisodeByIdResponse,
    ReturnType<typeof getApiClinicalEpisodeByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiClinicalEpisodeById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiClinicalEpisodeByIdQueryKey(options),
  })

export const putApiClinicalEpisodeByIdMutation = (
  options?: Partial<Options<PutApiClinicalEpisodeByIdData>>
): UseMutationOptions<
  PutApiClinicalEpisodeByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiClinicalEpisodeByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiClinicalEpisodeByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiClinicalEpisodeByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiClinicalEpisodeById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiHealthRecordQueryKey = (
  options?: Options<GetApiHealthRecordData>
) => createQueryKey("getApiHealthRecord", options)

export const getApiHealthRecordOptions = (
  options?: Options<GetApiHealthRecordData>
) =>
  queryOptions<
    GetApiHealthRecordResponse,
    AxiosError<DefaultError>,
    GetApiHealthRecordResponse,
    ReturnType<typeof getApiHealthRecordQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiHealthRecord({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiHealthRecordQueryKey(options),
  })

export const getApiHealthRecordInfiniteQueryKey = (
  options?: Options<GetApiHealthRecordData>
): QueryKey<Options<GetApiHealthRecordData>> =>
  createQueryKey("getApiHealthRecord", options, true)

export const getApiHealthRecordInfiniteOptions = (
  options?: Options<GetApiHealthRecordData>
) =>
  infiniteQueryOptions<
    GetApiHealthRecordResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiHealthRecordResponse>,
    QueryKey<Options<GetApiHealthRecordData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiHealthRecordData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiHealthRecordData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiHealthRecord({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiHealthRecordInfiniteQueryKey(options),
    }
  )

export const postApiHealthRecordMutation = (
  options?: Partial<Options<PostApiHealthRecordData>>
): UseMutationOptions<
  PostApiHealthRecordResponse,
  AxiosError<DefaultError>,
  Options<PostApiHealthRecordData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiHealthRecordResponse,
    AxiosError<DefaultError>,
    Options<PostApiHealthRecordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiHealthRecord({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiHealthRecordCountQueryKey = (
  options?: Options<GetApiHealthRecordCountData>
) => createQueryKey("getApiHealthRecordCount", options)

export const getApiHealthRecordCountOptions = (
  options?: Options<GetApiHealthRecordCountData>
) =>
  queryOptions<
    GetApiHealthRecordCountResponse,
    AxiosError<DefaultError>,
    GetApiHealthRecordCountResponse,
    ReturnType<typeof getApiHealthRecordCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiHealthRecordCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiHealthRecordCountQueryKey(options),
  })

export const deleteApiHealthRecordByIdMutation = (
  options?: Partial<Options<DeleteApiHealthRecordByIdData>>
): UseMutationOptions<
  DeleteApiHealthRecordByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiHealthRecordByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiHealthRecordByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiHealthRecordByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiHealthRecordById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiHealthRecordByIdQueryKey = (
  options: Options<GetApiHealthRecordByIdData>
) => createQueryKey("getApiHealthRecordById", options)

export const getApiHealthRecordByIdOptions = (
  options: Options<GetApiHealthRecordByIdData>
) =>
  queryOptions<
    GetApiHealthRecordByIdResponse,
    AxiosError<DefaultError>,
    GetApiHealthRecordByIdResponse,
    ReturnType<typeof getApiHealthRecordByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiHealthRecordById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiHealthRecordByIdQueryKey(options),
  })

export const putApiHealthRecordByIdMutation = (
  options?: Partial<Options<PutApiHealthRecordByIdData>>
): UseMutationOptions<
  PutApiHealthRecordByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiHealthRecordByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiHealthRecordByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiHealthRecordByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiHealthRecordById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiPatientQueryKey = (options?: Options<GetApiPatientData>) =>
  createQueryKey("getApiPatient", options)

export const getApiPatientOptions = (options?: Options<GetApiPatientData>) =>
  queryOptions<
    GetApiPatientResponse,
    AxiosError<DefaultError>,
    GetApiPatientResponse,
    ReturnType<typeof getApiPatientQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPatient({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiPatientQueryKey(options),
  })

export const getApiPatientInfiniteQueryKey = (
  options?: Options<GetApiPatientData>
): QueryKey<Options<GetApiPatientData>> =>
  createQueryKey("getApiPatient", options, true)

export const getApiPatientInfiniteOptions = (
  options?: Options<GetApiPatientData>
) =>
  infiniteQueryOptions<
    GetApiPatientResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiPatientResponse>,
    QueryKey<Options<GetApiPatientData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiPatientData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiPatientData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiPatient({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiPatientInfiniteQueryKey(options),
    }
  )

export const postApiPatientMutation = (
  options?: Partial<Options<PostApiPatientData>>
): UseMutationOptions<
  PostApiPatientResponse,
  AxiosError<DefaultError>,
  Options<PostApiPatientData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiPatientResponse,
    AxiosError<DefaultError>,
    Options<PostApiPatientData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiPatient({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiPatientCountQueryKey = (
  options?: Options<GetApiPatientCountData>
) => createQueryKey("getApiPatientCount", options)

export const getApiPatientCountOptions = (
  options?: Options<GetApiPatientCountData>
) =>
  queryOptions<
    GetApiPatientCountResponse,
    AxiosError<DefaultError>,
    GetApiPatientCountResponse,
    ReturnType<typeof getApiPatientCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPatientCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiPatientCountQueryKey(options),
  })

export const deleteApiPatientByIdMutation = (
  options?: Partial<Options<DeleteApiPatientByIdData>>
): UseMutationOptions<
  DeleteApiPatientByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiPatientByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiPatientByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiPatientByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiPatientById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiPatientByIdQueryKey = (
  options: Options<GetApiPatientByIdData>
) => createQueryKey("getApiPatientById", options)

export const getApiPatientByIdOptions = (
  options: Options<GetApiPatientByIdData>
) =>
  queryOptions<
    GetApiPatientByIdResponse,
    AxiosError<DefaultError>,
    GetApiPatientByIdResponse,
    ReturnType<typeof getApiPatientByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPatientById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiPatientByIdQueryKey(options),
  })

export const putApiPatientByIdMutation = (
  options?: Partial<Options<PutApiPatientByIdData>>
): UseMutationOptions<
  PutApiPatientByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiPatientByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiPatientByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiPatientByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiPatientById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiPrescriptionQueryKey = (
  options?: Options<GetApiPrescriptionData>
) => createQueryKey("getApiPrescription", options)

export const getApiPrescriptionOptions = (
  options?: Options<GetApiPrescriptionData>
) =>
  queryOptions<
    GetApiPrescriptionResponse,
    AxiosError<DefaultError>,
    GetApiPrescriptionResponse,
    ReturnType<typeof getApiPrescriptionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPrescription({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiPrescriptionQueryKey(options),
  })

export const getApiPrescriptionInfiniteQueryKey = (
  options?: Options<GetApiPrescriptionData>
): QueryKey<Options<GetApiPrescriptionData>> =>
  createQueryKey("getApiPrescription", options, true)

export const getApiPrescriptionInfiniteOptions = (
  options?: Options<GetApiPrescriptionData>
) =>
  infiniteQueryOptions<
    GetApiPrescriptionResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiPrescriptionResponse>,
    QueryKey<Options<GetApiPrescriptionData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiPrescriptionData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiPrescriptionData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiPrescription({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiPrescriptionInfiniteQueryKey(options),
    }
  )

export const postApiPrescriptionMutation = (
  options?: Partial<Options<PostApiPrescriptionData>>
): UseMutationOptions<
  PostApiPrescriptionResponse,
  AxiosError<DefaultError>,
  Options<PostApiPrescriptionData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiPrescriptionResponse,
    AxiosError<DefaultError>,
    Options<PostApiPrescriptionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiPrescription({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiPrescriptionCountQueryKey = (
  options?: Options<GetApiPrescriptionCountData>
) => createQueryKey("getApiPrescriptionCount", options)

export const getApiPrescriptionCountOptions = (
  options?: Options<GetApiPrescriptionCountData>
) =>
  queryOptions<
    GetApiPrescriptionCountResponse,
    AxiosError<DefaultError>,
    GetApiPrescriptionCountResponse,
    ReturnType<typeof getApiPrescriptionCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPrescriptionCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiPrescriptionCountQueryKey(options),
  })

export const deleteApiPrescriptionByIdMutation = (
  options?: Partial<Options<DeleteApiPrescriptionByIdData>>
): UseMutationOptions<
  DeleteApiPrescriptionByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiPrescriptionByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiPrescriptionByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiPrescriptionByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiPrescriptionById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiPrescriptionByIdQueryKey = (
  options: Options<GetApiPrescriptionByIdData>
) => createQueryKey("getApiPrescriptionById", options)

export const getApiPrescriptionByIdOptions = (
  options: Options<GetApiPrescriptionByIdData>
) =>
  queryOptions<
    GetApiPrescriptionByIdResponse,
    AxiosError<DefaultError>,
    GetApiPrescriptionByIdResponse,
    ReturnType<typeof getApiPrescriptionByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPrescriptionById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiPrescriptionByIdQueryKey(options),
  })

export const putApiPrescriptionByIdMutation = (
  options?: Partial<Options<PutApiPrescriptionByIdData>>
): UseMutationOptions<
  PutApiPrescriptionByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiPrescriptionByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiPrescriptionByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiPrescriptionByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiPrescriptionById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiInsuranceInvoiceQueryKey = (
  options?: Options<GetApiInsuranceInvoiceData>
) => createQueryKey("getApiInsuranceInvoice", options)

export const getApiInsuranceInvoiceOptions = (
  options?: Options<GetApiInsuranceInvoiceData>
) =>
  queryOptions<
    GetApiInsuranceInvoiceResponse,
    AxiosError<DefaultError>,
    GetApiInsuranceInvoiceResponse,
    ReturnType<typeof getApiInsuranceInvoiceQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiInsuranceInvoice({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiInsuranceInvoiceQueryKey(options),
  })

export const getApiInsuranceInvoiceInfiniteQueryKey = (
  options?: Options<GetApiInsuranceInvoiceData>
): QueryKey<Options<GetApiInsuranceInvoiceData>> =>
  createQueryKey("getApiInsuranceInvoice", options, true)

export const getApiInsuranceInvoiceInfiniteOptions = (
  options?: Options<GetApiInsuranceInvoiceData>
) =>
  infiniteQueryOptions<
    GetApiInsuranceInvoiceResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiInsuranceInvoiceResponse>,
    QueryKey<Options<GetApiInsuranceInvoiceData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiInsuranceInvoiceData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiInsuranceInvoiceData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiInsuranceInvoice({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiInsuranceInvoiceInfiniteQueryKey(options),
    }
  )

export const postApiInsuranceInvoiceMutation = (
  options?: Partial<Options<PostApiInsuranceInvoiceData>>
): UseMutationOptions<
  PostApiInsuranceInvoiceResponse,
  AxiosError<DefaultError>,
  Options<PostApiInsuranceInvoiceData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiInsuranceInvoiceResponse,
    AxiosError<DefaultError>,
    Options<PostApiInsuranceInvoiceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiInsuranceInvoice({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiInsuranceInvoiceCountQueryKey = (
  options?: Options<GetApiInsuranceInvoiceCountData>
) => createQueryKey("getApiInsuranceInvoiceCount", options)

export const getApiInsuranceInvoiceCountOptions = (
  options?: Options<GetApiInsuranceInvoiceCountData>
) =>
  queryOptions<
    GetApiInsuranceInvoiceCountResponse,
    AxiosError<DefaultError>,
    GetApiInsuranceInvoiceCountResponse,
    ReturnType<typeof getApiInsuranceInvoiceCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiInsuranceInvoiceCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiInsuranceInvoiceCountQueryKey(options),
  })

export const deleteApiInsuranceInvoiceByIdMutation = (
  options?: Partial<Options<DeleteApiInsuranceInvoiceByIdData>>
): UseMutationOptions<
  DeleteApiInsuranceInvoiceByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiInsuranceInvoiceByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiInsuranceInvoiceByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiInsuranceInvoiceByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiInsuranceInvoiceById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiInsuranceInvoiceByIdQueryKey = (
  options: Options<GetApiInsuranceInvoiceByIdData>
) => createQueryKey("getApiInsuranceInvoiceById", options)

export const getApiInsuranceInvoiceByIdOptions = (
  options: Options<GetApiInsuranceInvoiceByIdData>
) =>
  queryOptions<
    GetApiInsuranceInvoiceByIdResponse,
    AxiosError<DefaultError>,
    GetApiInsuranceInvoiceByIdResponse,
    ReturnType<typeof getApiInsuranceInvoiceByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiInsuranceInvoiceById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiInsuranceInvoiceByIdQueryKey(options),
  })

export const putApiInsuranceInvoiceByIdMutation = (
  options?: Partial<Options<PutApiInsuranceInvoiceByIdData>>
): UseMutationOptions<
  PutApiInsuranceInvoiceByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiInsuranceInvoiceByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiInsuranceInvoiceByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiInsuranceInvoiceByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiInsuranceInvoiceById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiInsuranceProviderQueryKey = (
  options?: Options<GetApiInsuranceProviderData>
) => createQueryKey("getApiInsuranceProvider", options)

export const getApiInsuranceProviderOptions = (
  options?: Options<GetApiInsuranceProviderData>
) =>
  queryOptions<
    GetApiInsuranceProviderResponse,
    AxiosError<DefaultError>,
    GetApiInsuranceProviderResponse,
    ReturnType<typeof getApiInsuranceProviderQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiInsuranceProvider({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiInsuranceProviderQueryKey(options),
  })

export const getApiInsuranceProviderInfiniteQueryKey = (
  options?: Options<GetApiInsuranceProviderData>
): QueryKey<Options<GetApiInsuranceProviderData>> =>
  createQueryKey("getApiInsuranceProvider", options, true)

export const getApiInsuranceProviderInfiniteOptions = (
  options?: Options<GetApiInsuranceProviderData>
) =>
  infiniteQueryOptions<
    GetApiInsuranceProviderResponse,
    AxiosError<DefaultError>,
    InfiniteData<GetApiInsuranceProviderResponse>,
    QueryKey<Options<GetApiInsuranceProviderData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiInsuranceProviderData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiInsuranceProviderData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiInsuranceProvider({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiInsuranceProviderInfiniteQueryKey(options),
    }
  )

export const postApiInsuranceProviderMutation = (
  options?: Partial<Options<PostApiInsuranceProviderData>>
): UseMutationOptions<
  PostApiInsuranceProviderResponse,
  AxiosError<DefaultError>,
  Options<PostApiInsuranceProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiInsuranceProviderResponse,
    AxiosError<DefaultError>,
    Options<PostApiInsuranceProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiInsuranceProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiInsuranceProviderCountQueryKey = (
  options?: Options<GetApiInsuranceProviderCountData>
) => createQueryKey("getApiInsuranceProviderCount", options)

export const getApiInsuranceProviderCountOptions = (
  options?: Options<GetApiInsuranceProviderCountData>
) =>
  queryOptions<
    GetApiInsuranceProviderCountResponse,
    AxiosError<DefaultError>,
    GetApiInsuranceProviderCountResponse,
    ReturnType<typeof getApiInsuranceProviderCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiInsuranceProviderCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiInsuranceProviderCountQueryKey(options),
  })

export const deleteApiInsuranceProviderByIdMutation = (
  options?: Partial<Options<DeleteApiInsuranceProviderByIdData>>
): UseMutationOptions<
  DeleteApiInsuranceProviderByIdResponse,
  AxiosError<DefaultError>,
  Options<DeleteApiInsuranceProviderByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiInsuranceProviderByIdResponse,
    AxiosError<DefaultError>,
    Options<DeleteApiInsuranceProviderByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiInsuranceProviderById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiInsuranceProviderByIdQueryKey = (
  options: Options<GetApiInsuranceProviderByIdData>
) => createQueryKey("getApiInsuranceProviderById", options)

export const getApiInsuranceProviderByIdOptions = (
  options: Options<GetApiInsuranceProviderByIdData>
) =>
  queryOptions<
    GetApiInsuranceProviderByIdResponse,
    AxiosError<DefaultError>,
    GetApiInsuranceProviderByIdResponse,
    ReturnType<typeof getApiInsuranceProviderByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiInsuranceProviderById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiInsuranceProviderByIdQueryKey(options),
  })

export const putApiInsuranceProviderByIdMutation = (
  options?: Partial<Options<PutApiInsuranceProviderByIdData>>
): UseMutationOptions<
  PutApiInsuranceProviderByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiInsuranceProviderByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiInsuranceProviderByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiInsuranceProviderByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiInsuranceProviderById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
