// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  deleteApiAppointmentById,
  getApiAppointment,
  getApiAppointmentById,
  getApiAppointmentCount,
  type Options,
  postApiAppointment,
  putApiAppointmentById,
} from "../sdk.gen"
import type {
  DeleteApiAppointmentByIdData,
  DeleteApiAppointmentByIdResponse,
  GetApiAppointmentByIdData,
  GetApiAppointmentByIdResponse,
  GetApiAppointmentCountData,
  GetApiAppointmentCountResponse,
  GetApiAppointmentData,
  GetApiAppointmentResponse,
  PostApiAppointmentData,
  PostApiAppointmentResponse,
  PutApiAppointmentByIdData,
  PutApiAppointmentByIdResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getApiAppointmentQueryKey = (
  options?: Options<GetApiAppointmentData>
) => createQueryKey("getApiAppointment", options)

export const getApiAppointmentOptions = (
  options?: Options<GetApiAppointmentData>
) =>
  queryOptions<
    GetApiAppointmentResponse,
    DefaultError,
    GetApiAppointmentResponse,
    ReturnType<typeof getApiAppointmentQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointment({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const getApiAppointmentInfiniteQueryKey = (
  options?: Options<GetApiAppointmentData>
): QueryKey<Options<GetApiAppointmentData>> =>
  createQueryKey("getApiAppointment", options, true)

export const getApiAppointmentInfiniteOptions = (
  options?: Options<GetApiAppointmentData>
) =>
  infiniteQueryOptions<
    GetApiAppointmentResponse,
    DefaultError,
    InfiniteData<GetApiAppointmentResponse>,
    QueryKey<Options<GetApiAppointmentData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiAppointmentData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiAppointmentData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiAppointment({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiAppointmentInfiniteQueryKey(options),
    }
  )

export const postApiAppointmentMutation = (
  options?: Partial<Options<PostApiAppointmentData>>
): UseMutationOptions<
  PostApiAppointmentResponse,
  DefaultError,
  Options<PostApiAppointmentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAppointmentResponse,
    DefaultError,
    Options<PostApiAppointmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAppointment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAppointmentCountQueryKey = (
  options?: Options<GetApiAppointmentCountData>
) => createQueryKey("getApiAppointmentCount", options)

export const getApiAppointmentCountOptions = (
  options?: Options<GetApiAppointmentCountData>
) =>
  queryOptions<
    GetApiAppointmentCountResponse,
    DefaultError,
    GetApiAppointmentCountResponse,
    ReturnType<typeof getApiAppointmentCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointmentCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentCountQueryKey(options),
  })

export const deleteApiAppointmentByIdMutation = (
  options?: Partial<Options<DeleteApiAppointmentByIdData>>
): UseMutationOptions<
  DeleteApiAppointmentByIdResponse,
  DefaultError,
  Options<DeleteApiAppointmentByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiAppointmentByIdResponse,
    DefaultError,
    Options<DeleteApiAppointmentByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiAppointmentById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAppointmentByIdQueryKey = (
  options: Options<GetApiAppointmentByIdData>
) => createQueryKey("getApiAppointmentById", options)

export const getApiAppointmentByIdOptions = (
  options: Options<GetApiAppointmentByIdData>
) =>
  queryOptions<
    GetApiAppointmentByIdResponse,
    DefaultError,
    GetApiAppointmentByIdResponse,
    ReturnType<typeof getApiAppointmentByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointmentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentByIdQueryKey(options),
  })

export const putApiAppointmentByIdMutation = (
  options?: Partial<Options<PutApiAppointmentByIdData>>
): UseMutationOptions<
  PutApiAppointmentByIdResponse,
  DefaultError,
  Options<PutApiAppointmentByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiAppointmentByIdResponse,
    DefaultError,
    Options<PutApiAppointmentByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiAppointmentById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
