/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PublicRouteRouteImport } from "./routes/_public/route"
import { Route as PrivateRouteRouteImport } from "./routes/_private/route"
import { Route as PrivateIndexRouteImport } from "./routes/_private/index"
import { Route as PublicSignUpRouteImport } from "./routes/_public/sign-up"
import { Route as PublicLoginRouteImport } from "./routes/_public/login"
import { Route as PrivateSedesRouteImport } from "./routes/_private/sedes"
import { Route as PrivateEspecialidadesRouteImport } from "./routes/_private/especialidades"
import { Route as PrivateEhrRouteImport } from "./routes/_private/ehr"
import { Route as PrivateDoctoresRouteImport } from "./routes/_private/doctores"
import { Route as PrivateClientesRouteImport } from "./routes/_private/clientes"
import { Route as PrivateCitasRouteImport } from "./routes/_private/citas"
import { Route as PrivateAseguradorasRouteImport } from "./routes/_private/aseguradoras"

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: "/_private",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateSedesRoute = PrivateSedesRouteImport.update({
  id: "/sedes",
  path: "/sedes",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEspecialidadesRoute = PrivateEspecialidadesRouteImport.update({
  id: "/especialidades",
  path: "/especialidades",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEhrRoute = PrivateEhrRouteImport.update({
  id: "/ehr",
  path: "/ehr",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateDoctoresRoute = PrivateDoctoresRouteImport.update({
  id: "/doctores",
  path: "/doctores",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateClientesRoute = PrivateClientesRouteImport.update({
  id: "/clientes",
  path: "/clientes",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateCitasRoute = PrivateCitasRouteImport.update({
  id: "/citas",
  path: "/citas",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAseguradorasRoute = PrivateAseguradorasRouteImport.update({
  id: "/aseguradoras",
  path: "/aseguradoras",
  getParentRoute: () => PrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof PrivateIndexRoute
  "/aseguradoras": typeof PrivateAseguradorasRoute
  "/citas": typeof PrivateCitasRoute
  "/clientes": typeof PrivateClientesRoute
  "/doctores": typeof PrivateDoctoresRoute
  "/ehr": typeof PrivateEhrRoute
  "/especialidades": typeof PrivateEspecialidadesRoute
  "/sedes": typeof PrivateSedesRoute
  "/login": typeof PublicLoginRoute
  "/sign-up": typeof PublicSignUpRoute
}
export interface FileRoutesByTo {
  "/": typeof PrivateIndexRoute
  "/aseguradoras": typeof PrivateAseguradorasRoute
  "/citas": typeof PrivateCitasRoute
  "/clientes": typeof PrivateClientesRoute
  "/doctores": typeof PrivateDoctoresRoute
  "/ehr": typeof PrivateEhrRoute
  "/especialidades": typeof PrivateEspecialidadesRoute
  "/sedes": typeof PrivateSedesRoute
  "/login": typeof PublicLoginRoute
  "/sign-up": typeof PublicSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_private": typeof PrivateRouteRouteWithChildren
  "/_public": typeof PublicRouteRouteWithChildren
  "/_private/aseguradoras": typeof PrivateAseguradorasRoute
  "/_private/citas": typeof PrivateCitasRoute
  "/_private/clientes": typeof PrivateClientesRoute
  "/_private/doctores": typeof PrivateDoctoresRoute
  "/_private/ehr": typeof PrivateEhrRoute
  "/_private/especialidades": typeof PrivateEspecialidadesRoute
  "/_private/sedes": typeof PrivateSedesRoute
  "/_public/login": typeof PublicLoginRoute
  "/_public/sign-up": typeof PublicSignUpRoute
  "/_private/": typeof PrivateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/aseguradoras"
    | "/citas"
    | "/clientes"
    | "/doctores"
    | "/ehr"
    | "/especialidades"
    | "/sedes"
    | "/login"
    | "/sign-up"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/aseguradoras"
    | "/citas"
    | "/clientes"
    | "/doctores"
    | "/ehr"
    | "/especialidades"
    | "/sedes"
    | "/login"
    | "/sign-up"
  id:
    | "__root__"
    | "/_private"
    | "/_public"
    | "/_private/aseguradoras"
    | "/_private/citas"
    | "/_private/clientes"
    | "/_private/doctores"
    | "/_private/ehr"
    | "/_private/especialidades"
    | "/_private/sedes"
    | "/_public/login"
    | "/_public/sign-up"
    | "/_private/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_private": {
      id: "/_private"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_private/": {
      id: "/_private/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_public/sign-up": {
      id: "/_public/sign-up"
      path: "/sign-up"
      fullPath: "/sign-up"
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    "/_public/login": {
      id: "/_public/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    "/_private/sedes": {
      id: "/_private/sedes"
      path: "/sedes"
      fullPath: "/sedes"
      preLoaderRoute: typeof PrivateSedesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/especialidades": {
      id: "/_private/especialidades"
      path: "/especialidades"
      fullPath: "/especialidades"
      preLoaderRoute: typeof PrivateEspecialidadesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/ehr": {
      id: "/_private/ehr"
      path: "/ehr"
      fullPath: "/ehr"
      preLoaderRoute: typeof PrivateEhrRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/doctores": {
      id: "/_private/doctores"
      path: "/doctores"
      fullPath: "/doctores"
      preLoaderRoute: typeof PrivateDoctoresRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/clientes": {
      id: "/_private/clientes"
      path: "/clientes"
      fullPath: "/clientes"
      preLoaderRoute: typeof PrivateClientesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/citas": {
      id: "/_private/citas"
      path: "/citas"
      fullPath: "/citas"
      preLoaderRoute: typeof PrivateCitasRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/aseguradoras": {
      id: "/_private/aseguradoras"
      path: "/aseguradoras"
      fullPath: "/aseguradoras"
      preLoaderRoute: typeof PrivateAseguradorasRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateAseguradorasRoute: typeof PrivateAseguradorasRoute
  PrivateCitasRoute: typeof PrivateCitasRoute
  PrivateClientesRoute: typeof PrivateClientesRoute
  PrivateDoctoresRoute: typeof PrivateDoctoresRoute
  PrivateEhrRoute: typeof PrivateEhrRoute
  PrivateEspecialidadesRoute: typeof PrivateEspecialidadesRoute
  PrivateSedesRoute: typeof PrivateSedesRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAseguradorasRoute: PrivateAseguradorasRoute,
  PrivateCitasRoute: PrivateCitasRoute,
  PrivateClientesRoute: PrivateClientesRoute,
  PrivateDoctoresRoute: PrivateDoctoresRoute,
  PrivateEhrRoute: PrivateEhrRoute,
  PrivateEspecialidadesRoute: PrivateEspecialidadesRoute,
  PrivateSedesRoute: PrivateSedesRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignUpRoute: PublicSignUpRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
