/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PublicRouteRouteImport } from "./routes/_public/route"
import { Route as PrivateRouteRouteImport } from "./routes/_private/route"
import { Route as PrivateIndexRouteImport } from "./routes/_private/index"
import { Route as PublicSignUpRouteImport } from "./routes/_public/sign-up"
import { Route as PublicLoginRouteImport } from "./routes/_public/login"
import { Route as PrivateCitasRouteImport } from "./routes/_private/citas"

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: "/_private",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateCitasRoute = PrivateCitasRouteImport.update({
  id: "/citas",
  path: "/citas",
  getParentRoute: () => PrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof PrivateIndexRoute
  "/citas": typeof PrivateCitasRoute
  "/login": typeof PublicLoginRoute
  "/sign-up": typeof PublicSignUpRoute
}
export interface FileRoutesByTo {
  "/": typeof PrivateIndexRoute
  "/citas": typeof PrivateCitasRoute
  "/login": typeof PublicLoginRoute
  "/sign-up": typeof PublicSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_private": typeof PrivateRouteRouteWithChildren
  "/_public": typeof PublicRouteRouteWithChildren
  "/_private/citas": typeof PrivateCitasRoute
  "/_public/login": typeof PublicLoginRoute
  "/_public/sign-up": typeof PublicSignUpRoute
  "/_private/": typeof PrivateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/citas" | "/login" | "/sign-up"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/citas" | "/login" | "/sign-up"
  id:
    | "__root__"
    | "/_private"
    | "/_public"
    | "/_private/citas"
    | "/_public/login"
    | "/_public/sign-up"
    | "/_private/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_private": {
      id: "/_private"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_private/": {
      id: "/_private/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_public/sign-up": {
      id: "/_public/sign-up"
      path: "/sign-up"
      fullPath: "/sign-up"
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    "/_public/login": {
      id: "/_public/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    "/_private/citas": {
      id: "/_private/citas"
      path: "/citas"
      fullPath: "/citas"
      preLoaderRoute: typeof PrivateCitasRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateCitasRoute: typeof PrivateCitasRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateCitasRoute: PrivateCitasRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignUpRoute: PublicSignUpRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
